apiVersion: v1
kind: Secret
metadata:
    name: honcho-redis-credentials
    namespace: honcho
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7qVkkGWKNY3eANFIm+y1ALtnD3HtZy6IweLkL6BvNAOkNfk531G6uxvuvcI=,iv:HJzxjxVGj9EBXWW+8hTwxTvLw9bV7Q0mzfA++cDxjLM=,tag:XP7o5OdkXKo02CQuIa265A==,type:str]
    cache-url: ENC[AES256_GCM,data:m96GUv2vLJjafQVEcQkEFLujK6mXIMlf5i4vJgFKyWv45iDvRzqbDaS3zgbJN4jekwy9Oz7da7X+m0rYYEMhJ/CyJtSrwRcrcaGOVsPQ/ix+vDJnLM/YqDiLR2fGndxYIs9NMg6/jEzJwiMN98lOsw==,iv:kfw5iyVOUkQM+Y8N4VoC+FColaK/WRBvjqAH/sPFTV0=,tag:Mgxcj/WC7affXbbyX2AVTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWlFXTGdxUHY2NXpsWVZ6
            ekR6U2t2ZG1vNk1zUUdDM0pIL1dGakxWcUZ3CkFlN2YycnRFdkRKcVNjTFF3bEtt
            blZOWnExK29Mdk91UW40S0pJcUsyUWMKLS0tIHR5Q2FJeE1HTGNHajBlZXMrSGx6
            dC9QblA4OEJxUlpJenJ2TE0yb2hGdlkKEFTx+rck7Yl6RJQQ/RAhUBfYwYn+GpwF
            JlnMCCa07uCo+u2OyQXE5iLc0hTy4tzU3ovMPoUbrLWfkcQgYJ0MbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:32:49Z"
    mac: ENC[AES256_GCM,data:XYTGZxyq007G7IBmRvEs+LvfHqcFQbyMb6cHQIKQdzrzL88Ex5xHgRAS0NgeGOmn0cchpd7etK1z+lXXpL91OfxDjPBlEupXXQ5Tc8AC5sm8oFoAch07UAp5MT0iUAaFm/ugpqiB/TZkmDfT5zwTnCRFuFYazp8HbVEA+JVLJWY=,iv:FEAiAhQwffXBSfsToOPRvf5ltmK3qbsVi98j3jwuh+s=,tag:U9c5mtxBA0hHmfcSGwAWzA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: honcho-litellm-key
    namespace: honcho
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:446u3MYaWMGAu0MN5GLG8dUyBL62Cq2oIg==,iv:Hg40koWD0KXDrnl7gBUB+hv2w7nA5lc7po9/e9ihSsw=,tag:W+aaAOonRM5gaDAzSDfN+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWlFXTGdxUHY2NXpsWVZ6
            ekR6U2t2ZG1vNk1zUUdDM0pIL1dGakxWcUZ3CkFlN2YycnRFdkRKcVNjTFF3bEtt
            blZOWnExK29Mdk91UW40S0pJcUsyUWMKLS0tIHR5Q2FJeE1HTGNHajBlZXMrSGx6
            dC9QblA4OEJxUlpJenJ2TE0yb2hGdlkKEFTx+rck7Yl6RJQQ/RAhUBfYwYn+GpwF
            JlnMCCa07uCo+u2OyQXE5iLc0hTy4tzU3ovMPoUbrLWfkcQgYJ0MbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:32:49Z"
    mac: ENC[AES256_GCM,data:XYTGZxyq007G7IBmRvEs+LvfHqcFQbyMb6cHQIKQdzrzL88Ex5xHgRAS0NgeGOmn0cchpd7etK1z+lXXpL91OfxDjPBlEupXXQ5Tc8AC5sm8oFoAch07UAp5MT0iUAaFm/ugpqiB/TZkmDfT5zwTnCRFuFYazp8HbVEA+JVLJWY=,iv:FEAiAhQwffXBSfsToOPRvf5ltmK3qbsVi98j3jwuh+s=,tag:U9c5mtxBA0hHmfcSGwAWzA==,type:str]
    version: 3.13.1
