apiVersion: v1
kind: Secret
metadata:
    name: honcho-db-credentials
    namespace: honcho
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cTLm+jWQ,iv:4jetktcKQT1CpEwXbXixrPLhSb+KYi9cwypginaye68=,tag:KD+o/ByB+s++5PPmT+dWKg==,type:str]
    password: ENC[AES256_GCM,data:70eQIDoLIsnyVhMQCWA0i020XcEh8L0tiqpdzo4f6yzdxGtRzz4b1qOKLRI=,iv:YYrahePdRkM7m4cSmIaFuBG+M+jW9V5GXa7j6WnFY8U=,tag:4+6Sd3EM/ekDIIM3YnSWBw==,type:str]
    dbname: ENC[AES256_GCM,data:EYT2fvrw,iv:JpO8264QIoIcJwueHTgWjnJYGldH7tuNtfZMdibxxEA=,tag:dFNFdBQVkUaF/6s2e5woSg==,type:str]
    connection-uri: ENC[AES256_GCM,data:TmfKHDml8JbkchzMSd3+O7oGLxIIuxLIfQleQu5yY83KnGGw4COdJzol4Rb0z1lgYi4//BkDEVTLpvQN9c09GyTYBpD2Ouxq7KXi13rQVjGHnh2yLNWaqwQmeTFJW/PbUG+KOUgg/+tOoc6iSIXgUG4gcWmoQ3nF9btMq1GQGf0bZmBD,iv:vPkeLODgt3cmoW5sUuLTK7cKUIKe+qJ7qhWdFQA33E4=,tag:PIp7EAj5xBZmIWiLmv8L6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRWZMaEJaVUkvVGcwR0gx
            UHFQWnk0M1FNbjN5WUFNTkNwSGhTOFY4RUNNCkFLc2I3RXNZYWRBd21CVEx1S1k5
            Zi9kRU5MK1QrQ3kweGxzYkIzOUZnWFkKLS0tIGtGREpOd0pCNEdPQVhUWnpheFhj
            YlJESW1qKzBnZ0NFVWNmMWxVcEduVUUKguqV1h609QPrbDqmlSuR0n4SjLn7ubj5
            qO+4vyY79GKakXcMH67Jf+vYrHOTIhatQOQubKJglonondJH+cSdJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:59:43Z"
    mac: ENC[AES256_GCM,data:cIbVm9Syc7KOvN9htVUx7fl72FYY1Ahc3XSvXsIXbqvlGSOhEDqqbTiJG+RIFnW3Ie/2K1IsHrcjHNBGdA5CoyJKYURwPPghWlW0WmK4MhyY5/XHVTXCrb68E2n6oZMO+thV9D2KCTjmGNvFnaMsoKyWgpQx68evdQXS6Rs47V4=,iv:h49np9tMzI5P9bLaIEKc+AY9iQfqfalZupNZpRkHVsU=,tag:yn3EO57Ng0nndv2MsXIPIA==,type:str]
    version: 3.13.1
