apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:rfVYT64wi0hvB24oGD4=,iv:1FVbch8e7IE94M0oK4rCzOqz4FE06vCAaIPyZwG+qz0=,tag:o80EUCD0ZtK+rQ8ORP5S2Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Oxw74VMl7YcTp0eO9Nw9flGGB4tgHNdHYx6j7lhWnZA=,iv:8997JoZztPQmDOtwOq8euIWF2YlMIkq9uegI8N78US4=,tag:3eH1FQjuKN0OT14U5zXp7Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: honcho-minio-backup-creds
    namespace: honcho
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdFd2ZGVOZnZYNDFTVVN0
            bTFtbTR6VnJmZGRJNHdhaFRPNmZ5bEcxL3d3Cm4yaEVEaFJWM0sxOVZZRjRmUlQ5
            U1VxQUVRVWUzbGYxUUVzaEZ4bWZic2MKLS0tIERiSWtKSVVLRUQzSTJSSWk5blJJ
            a1JHQWFCQmlaUDJuWWg5Tk9BckFTaDQK5MSOTE9z26yykkwMgRyGUQM+TpBEdp70
            0OWx6dVXPziABrVLgVCk+aM1VOL/Sa2qnxBKIi137IJ+2kwsMs92+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:28:05Z"
    mac: ENC[AES256_GCM,data:xm23D5EMLwRLDJQANJnWm7mV+8SYHJ3gffpZYL5COFsk2LOzcFHDWQRqqVeBc/Chqhr7pWq+w+LaUa5L5G4qJUb1Vu/uQoEkc1izejftaNjhrmiC/X90uxWGf1GLnuX7YqMkVXohbaDZNZGxkj8b34e5lwD88LvR+G6jw6lxPaU=,iv:zNiH9ij+SbrBngdRHgFHQGjMRJIkwTmPmPxAFhJ93ts=,tag:MaeoPOCkh1MR5ukj1a+qvQ==,type:str]
    version: 3.13.1
