apiVersion: v1
kind: Secret
metadata:
  name: honcho-mattermost-webhook-url
  namespace: honcho
stringData:
    #ENC[AES256_GCM,data:QrVv+CI4F7IkMSv4RcWvamrf4wtqek8udzL4V/Ftg8Y9Dp06BVD24iSFkGGpZnA11mI+,iv:Veh7AmfYNnKlzv+T7X1Kv0TzukVwyO2dce2901ZYeQY=,tag:0bSyKnzOMiugx4o85kPDXA==,type:comment]
    url: ENC[AES256_GCM,data:xYPgxccTzoPbB1IyBjSAFkqy/G8tZ+p9noI/RCv4ETuKg8sDYcBsbq0Pi2fBqbcoR4oIm+8kFFlW,iv:7J6otLGr0NWp26AHI2MOsc+upiyxd4tPR8uP1xh6BsA=,tag:34Aw3P3RXcdmRS80x6Tl+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiblNZN3E4dS93a3JCWjNx
            VTZIaFlrakxQTUVXK3dnU0xvamF0K0NmNHh3CkJJS0IxNWpGWnIwWmxpNnBMWWc0
            Q1JGSjZHZ3pQZU1ucEw1SXVmUFM4REUKLS0tIEQ1cUFoWmsxOVp6ZGE2Ry9VN3hq
            ZXZ3dWFmaWllUkdDK1F1VXZVQTlza2sKPj1TYIakjPO94LDklpncOiwCtnwgPr8v
            akJ0Pqy+byFeQxix5Pi5nU5tAaaWo5GJqxb8CiRK1V6OYV9x4oaQBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T22:01:56Z"
    mac: ENC[AES256_GCM,data:UIbgXlerUxmZgpMCF/BJ7bRSyY+oU8URAA62C33S3H0s3JOhKEHWiuQNiBjVg10fYSa24NY9STefRAp/0vaLe/6BPMh9mIlcIuCG/vb08bValH6RXoLbUiYCt4rvP7VjTqVV2J2qZ3doinQizfIa5tON8s6iXCF3j7T1INcmN8c=,iv:fyt5R8zlLTtcQE9OBcOjzUJV3oRaI9mTDsLSCiT09zk=,tag:e6XE7wETjvyYgaVdee76Dg==,type:str]
    version: 3.13.1
