apiVersion: v1
kind: Secret
metadata:
    name: honcho-redis-credentials
    namespace: honcho
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wNTQwZWX9XNA+DsL0rM5cdlZHS3BsoKnIhh16z1jukAmzov5S7waWsb4lOA=,iv:wNCDuoCE0AOF8F7nFnPz4ZAIgcx0oWiFpjO9i07h498=,tag:zxE0TFE295Xqe/K16sAUtw==,type:str]
    cache-url: ENC[AES256_GCM,data:eQ/84tEyJaxYnHVdK06D8G9eFTxNtaFjfrHQ8S4dqwfQ5phb+Pg4eLXtUfcYYX6N2KxQOh5aHPHzE5BvAaSbjtfgG7Kg+ZLKlbFnye0b/LyYII0mayvCC76R52/Y3E76iSShbaIAN4qQArXnIoKmSA==,iv:QDUIVdDbEes4BXLBtobnaYvBUXoLYRuRf14uUg0GBxg=,tag:9YYkjF6PKNeyiD99LchN4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQjZVbE11b2wrZGNFYWJa
            Q0pTQVJKY3paNGw5cytEcXdmM1RtdWxLWmxNCkZrNlpITE8vbkg2OTZLQnNWQjdU
            aGVVcmlyVE0xVDJnSHMxYkEyYVIvNFEKLS0tIE43cHVxbnk2KzMxZ0cvTmNnRmhN
            R1hMS3IzWnc1V1NGeVpqbDdWeklkR0EKgNNUVL8rHCZSP6mU/hIvE/swpudTUvqy
            NWAr3D95YxNGJkK/gG97VyfysLVbc1efK2EsMtqdHlE8nCVWK8Xa8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:05:10Z"
    mac: ENC[AES256_GCM,data:Pw7iDuX46EAVxmgZYhu9TmECobiLXwcVavOESmJgctL58kpnjt8pTd4xQ8Bm2w1Vsqjm1KrXTXGCv2KYEDQwDtEIZzr+rIigadHI/PlWyHWnvc1SoPmkqFCCeWJgJxsj+L2F1aWLUBzYSYK5Rh2DtSwMZx1iduTmbXrHIqEB1hA=,iv:+JRRvjWuX+joGd9I2VZlmGKYM9mBdu7njRxHSowKM8Q=,tag:BLhTrzC2lJMyiTTKv6R5ow==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: honcho-litellm-key
    namespace: honcho
type: Opaque
stringData:
    api-key: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQjZVbE11b2wrZGNFYWJa
            Q0pTQVJKY3paNGw5cytEcXdmM1RtdWxLWmxNCkZrNlpITE8vbkg2OTZLQnNWQjdU
            aGVVcmlyVE0xVDJnSHMxYkEyYVIvNFEKLS0tIE43cHVxbnk2KzMxZ0cvTmNnRmhN
            R1hMS3IzWnc1V1NGeVpqbDdWeklkR0EKgNNUVL8rHCZSP6mU/hIvE/swpudTUvqy
            NWAr3D95YxNGJkK/gG97VyfysLVbc1efK2EsMtqdHlE8nCVWK8Xa8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:05:10Z"
    mac: ENC[AES256_GCM,data:Pw7iDuX46EAVxmgZYhu9TmECobiLXwcVavOESmJgctL58kpnjt8pTd4xQ8Bm2w1Vsqjm1KrXTXGCv2KYEDQwDtEIZzr+rIigadHI/PlWyHWnvc1SoPmkqFCCeWJgJxsj+L2F1aWLUBzYSYK5Rh2DtSwMZx1iduTmbXrHIqEB1hA=,iv:+JRRvjWuX+joGd9I2VZlmGKYM9mBdu7njRxHSowKM8Q=,tag:BLhTrzC2lJMyiTTKv6R5ow==,type:str]
    version: 3.13.1
