apiVersion: v1
kind: Secret
metadata:
    name: honcho-db-credentials
    namespace: honcho
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mu50m+oQ,iv:tThG9CdWqkFpOQvOVG4HOonOIKXPm6CyXNAaqS8WnnU=,tag:7SJa5pRHfAROWdClVv4DhQ==,type:str]
    password: ENC[AES256_GCM,data:jvfpPEBkXEqkq/ha3WdniLTFsVY=,iv:cireTw8FEveVWb2WLHaO6ne9qFdnq8DntptBWl3T5qo=,tag:P8L2BXNJv9udOfCQPfcOsQ==,type:str]
    dbname: ENC[AES256_GCM,data:HRYPhzMx,iv:5icmXzMPqV+DksRm8JFP520j+riKXXTviFyg4tmfQPU=,tag:vXINP8QpTRuDYl4CMx1Dng==,type:str]
    connection-uri: ENC[AES256_GCM,data:CjOf6vVpeHjhRhoQiT0lpNTbBbpBihD1k1a+Ik6xB6hfaAFLbueAMjD8fZYbUFj4znZ07Ahctg/9X3knLUYoRH+hOw3MwFKDNe4z52VDULr5F8ha3f1E1IgZ9xZmSDRA4IA=,iv:bLoy9E86y0Sr5kP8JbWTzYL/EQ+BCuaZ09rNOLH+wsQ=,tag:uh3UudJAowpFps0EfHdoVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOE83ZVk3MHVkdG43WU1G
            OGJobnV4YWRQZFRrQktBTm4rb04rQlR1cUM4CmZ0MWtJRjVxTWNlT3dqa2tBQkxj
            WnRQQnpQWmY0bXF0bk55aEZ0emI1bDAKLS0tICs4U2tsRGNZcmw3MG9PenUzYnVE
            c1BpTFkwOGFGNFlURzZZR1NqYU5qTXMK+dPccaKYA/LN/1GoJA7l1Adf6bjlwuX/
            kGEXXd/MjMCs+DBE8XJ14a6PyRjO9vZbMgb6dhSP8NmITaB+928FHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T11:04:59Z"
    mac: ENC[AES256_GCM,data:DgCcs3Jx+GBz6ji67dCA+zhpqykgeCj5oE19m4/xn0kZ4nOKIYTHbl9Kj8ahiu/Qm7g5uoO6sAgs6E5aG0ccfkgdLDp//P5nIUE28ZjpRrvMuKIVhrfeCPzs4iBJ5xf3Y5/LeVhvqCaF2tXVfv/PkFwBBAjKDoISSjuBwB+WkUY=,iv:NKun5PW66/LW1Ipnifv3NZg92XoUcxt0oEa3Vd2BMUY=,tag:eAcWb8ko4aFq8610gTWAPA==,type:str]
    version: 3.13.1
