apiVersion: v1
kind: Secret
metadata:
    name: honcho-mattermost-webhook-url
    namespace: observability
stringData:
    #ENC[AES256_GCM,data:BnZ20qZMW/P3s0eQ7O3g4lQwZNDTGnG7XnFRq2VHNcBTpLpkBOwmYCEC7sARAkZoX9En,iv:X86fVlJU02C6SQci6DJIS4NCeez+C3xuOELqKThcd5g=,tag:8S236+nWnmSokTrCkHdenw==,type:comment]
    url: ENC[AES256_GCM,data:QqaYt6pl/As35yQ0n1kWgWiAnezZfLQPMR8cJ2rfI3AS2KUlMVDWMm5RJkaQHnxn6RU+4kOubifk,iv:4vZ3eIxDmaYUeN6rtCRnrETImEt+QlWj1uIePjB575s=,tag:KRBKPIoYDe+lI7m+de9GFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacWhINytEYzBGV3dWWXdM
            NFVUQmZIVDUxZjI3L05YY3VHOTRMT3pyRFRBCmR3QUNYRnZRL2VMcVhmbFVyd0Q1
            M29zVXoxcUZNYVNXazlkVDVTTHBWemMKLS0tIFdoR0p5clM0SFNlVkQva1pDZDVz
            THQ3V2o0cGtGdGdtK0Vra01tV05KRFEKvTe8c2UEanEOhR1Suex4LFlp3ecCWoXV
            bUYEh6brcw7+d2Hi61k6Hi2Rg7qbhUVnv83W6ge6VhOZicXw75Hf1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T21:49:04Z"
    mac: ENC[AES256_GCM,data:tZAB7zh8yJIdvN/BR+a7z9vJCB4pBV0YK48DG6YCks2Dn2T37MwGVXVvYGgxeLcKeMAeQqyQGNowApk8e0ptWD7n5FcN2bp2QzVHIo7lCD5lxyhUM4LbntJXq9MN9g0thvJCLHEElRQpQIfpDaulTjBBub/1EpULEtwpJsioYkc=,iv:Y/FJy1rcrM4wdxEraFz+VqZSgnINZSZeesbDlJjMzjI=,tag:Fp5QYwJGndKrTd3VzlsMMg==,type:str]
    version: 3.13.1
