apiVersion: v1
kind: Secret
metadata:
    name: tldraw-db-credentials
    namespace: apps-tldraw
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CQKRdQ4W,iv:x37Lwa1V/DvKAYPwxazPlDfqA4ZOzR9QV3JAO5pc83k=,tag:ujE+qI0TGEQgbyTXk5mBhw==,type:str]
    password: ENC[AES256_GCM,data:eaVgpyWFYXHByjRS3+gI7fkm5AW70LVy,iv:+5sFmWky8V82Lz0hmovEEk/r5Ul+5NGjsGPUuAmEsXY=,tag:7XHDiXoSNxuGo9Pr5s67rg==,type:str]
    host: ENC[AES256_GCM,data:Ou7/5X61PyeFCtKbUeGJiY7hCVxkUIea3n575yMR1mm0yLecFSUMbry1,iv:mTmpaF8cUzAhV6EURdNYECtJMvOu0jMwWhBdkcve0xc=,tag:K+5APZXHwZNCzFYV2cUy8g==,type:str]
    port: ENC[AES256_GCM,data:h0uOng==,iv:gcynEbCEwizXDOLw7hlFuvend157B+Mwc2sDC0/A3Ps=,tag:X+ycoGFhBX2uqPPqQXz/SQ==,type:str]
    database: ENC[AES256_GCM,data:Ulvi4NRF,iv:HuERWhnpeKvqpATsonVOJ0mX6+JBe+LrYh6qYzQuI6Q=,tag:O0+gkB02yPB1tWKqzD0egQ==,type:str]
    externalConnectionString: ENC[AES256_GCM,data:XoLtG+J/4XNLfXJ91n6Fw81UuYsPK740/a+aa/liqRqwaPtdUaL01A/h9IGd76jFZ6CuLeESQLitbLgCafqwUa6GN5b++UI058EJNw==,iv:wHW86AIPTlRgcVsxi5WBXVHA4y4cWaUwMXplMC1Kk6Y=,tag:hgSnZmxXLO6C1x0+RKjT4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VkhvaVZzOFVwVUFybVYz
            eG9QSTBYa1c2bjA2Qld4U2xpenZzTmxFSW5JCk5IYm1qMHA2aUIweTY5enlqNXRE
            TEVPMDB0NEJOOEFqb01iMFg5WVRlZDAKLS0tIDFZRHZmMFQ4YS9hMGxYQmtHUWV2
            aVJBRXFycC9YSUV1T2NzY296Y0pseDAKFdcLngg+JkenejKDwNi/GUUaSdgrPlc1
            vRWjxO+XM/AJbA0dh+nESDhfMPyFkWHSHyAoaiv04F2i5hNraRfX3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T12:29:02Z"
    mac: ENC[AES256_GCM,data:cz8wuP2yhdNmdwwfsS1WFWzOi9WFXLaK3+zFCZrg984ESHRhuZX4ec7uyw0jh7dFiLGNAy1uwsd1IohJ6NTRp6ODyjbqi88kkaFdbHuTnsNJ3ombwERIyfQ81Rwsdkd7DpjS0taCIKXRy3ToX3sMjOXDnwGF2ff7m1LI0+5Ld3g=,iv:NUh8fBKA6WWTS1HRJ7nDuyL0EQXwM+Lb/fwlyq94mIY=,tag:KJ1i9rUpjzN4wTi2ysXN0w==,type:str]
    version: 3.13.1
