apiVersion: v1
kind: Secret
metadata:
    name: itsaplan-tunnel-token
    namespace: itsaplan
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TWTog7grDdYPX2DG9d9cAyAWJfWkoEr7UjiqHi5GZQPzfH+fc4LBcy7UkHC7yZ22IDLny+lq96w3qbi2qdLM2Sao7NFF8aFLbTSVNGT4zrwvnE7U7eVdQg9igYg1bODA/ZuY4ohs3gDHECNcJ29iAZrey3ILVsONiCCJ9h7gr4/NScz4OFJKZ/Hj9/ldqvH/LCr2AtiZzTi9rUjl0q1Luw51WnjsRH4K1EgjNwMa0LzdrUyeHgkt0A==,iv:lTZ8IqQpS8YNT7uX1yfQ9ZeZbIzjnQiIIQ4K2tvNqYc=,tag:sbP6CS6Erdq5jJw5e6DF4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdkFLRGlSM3MrVGhTclh2
            TDJZZGU0c3NhdGRqYmt0UktlNVowekZLa0NBCjJtU1c2VnFXcTVzVkwxYzcwNkEr
            SGRZYVp6eXF6RVdGS3R0OG40MElOWWsKLS0tIDlCSVhQYzRKbTZEQ1Jua1F0eWlK
            ZWxyaG5OaHdwcnNQRFM1MTVqd0xaWGcKj+Oumw0tDyLxPQ9fF+ZiVar+RpDrxeOq
            cOpc+WQX/ybB2L0WwlCwuuTNocL9T5aGiSk0HkvV8hYMoLcrBZRM7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T21:04:04Z"
    mac: ENC[AES256_GCM,data:M7RGxTwFGR4naBXfgE02X/d1cw8Nue4/3SGr6fEs+kL/3ec6WUPzZrzbKD9Eg7sck1YBT4cO5SDH1iFcg09HKbD2d/mXEz9jeYheDGXxQro2IbiTiMO0Amgl4dUliA307a9B2cVRJ+ITS+ZH1Fz59UnzFBM1aFLqXjKhssR27hE=,iv:iklFd/FENUvTkwnu6NL24VKc5g043DjRB8iWLMWnhKg=,tag:W5SQzsZowuNjbWZWkfxTlw==,type:str]
    version: 3.13.3
