apiVersion: v1
kind: Secret
metadata:
    name: itsaplan-minio-backup-creds
    namespace: itsaplan
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:JnPWo/spnZMW8191rmJ7ecxkgMA=,iv:HWrmrvD12jRS9QvZE3d8/2aNUJWV6FLFz7M189WBuY8=,tag:gqnedNEzjyGZQ8n2wdr/bw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:6dzLr5srWogSKSpdD+kP2ZHt/V4MakiGgki+lSB0JkhlGObjLo4dRw==,iv:QUoatQlzpJ71kehj4UOx22R6JyCicCkX/6vx6GAsixU=,tag:kusRQD8W9oNCr0FbBSj70w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraWJDOWN4K05LWjhtSHRV
            Z2pEdFpySWdFQnRuTEtCZDJyS0tRdk91NldjCkRVU2s3c2hTMlBOcDNsdXRLNHJv
            R1J6TnppVFJ3azVscWZvTDliK2svRnMKLS0tIDYxaTZ0c05PRlNtVTE0K0ZVMTUw
            OVVQK2ZtOFVGL1hsNE9Gd1hkZWhyLzgK2tW8t/igaQZUdeiYiBwIgAP0PfEtbiTN
            CeKa2KlB/GtfdRF7dAsuxU8ScRyYWpkB1fw//7FPNDkOrqqZ8Fq81A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T13:09:28Z"
    mac: ENC[AES256_GCM,data:nPp3EOMGUeBiidgLzC/40KYonHa/Ewy6NupIqw4T+w/E+E3t/14974tGQv/xmnvFFrMe+MnOi/tcc5zwPfskfxFJkrrb2n+sICJbUPCOp46J5z6k2lyuTdk14kYU2bRh9ugIpI81mcF6TJDQlB+DEAlCUAKlFLGws4VkUYrCiow=,iv:lH36pZS7HJhayqDPVv8AWTHaUNQgeEiC7bbzi5Q4Mp0=,tag:lR37Yp9YZxkoTTwXYyI7XQ==,type:str]
    version: 3.13.1
