apiVersion: v1
kind: Secret
metadata:
    name: itsaplan-minio-backup-creds
    namespace: itsaplan
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:yX9igqU5u6ciQtwWArlmIu28TZk=,iv:X9rSdaL5eBQcGSP/JdWqyHXMvU+El8XTNHJ1v3zyxzw=,tag:j6uGbPYgDfB/xj/XrUu8MQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:QmVEED/uZMYn4xe3pqQcAjt7XijhPgc60BFJ7W185OnkPF2r+gMdMw==,iv:yhC0SaLeXPG0vRzDz1ACOrXUAve1v6+vAOXIkwxuHrU=,tag:3VWfbINjZCaHgc1nwO9j1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETmxkOFZ5M3NWUjVxTTRw
            OWl4cW1TNTFWUUp2dEVsL0hFQUtiZXJXem5FCmNKUGppaFRkOGFiNVBwQmpRTllG
            R1luTitGN2hRb2I0WG52eGZ4ZytyU0kKLS0tIGJUa2NEbWRDUEkvVnpMdjBXT0px
            a1BvZGZMeVlUQk8vaHFYWHBTYU9Sd2sK+Gt9Cwj5b7ThyJALLA04T45pqJQwVD9B
            sRCj2zvAPeuGh0xSS/WttKnFWbpSJQ7LX8g0eBAOrjUUTWE24hl3cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T20:28:47Z"
    mac: ENC[AES256_GCM,data:47c35zWxmSc4O1M7OMhHDs+7UqTtOuRWYV63W5BErXghgU80Lq5sDGsMO+S4fiTNsRHjZKwNTCiPgSGHiqIf0QsV74KYqqZwWBvwH93mwnJ+0EU9AmwKX7XZ4QGf8oVKct7yZ+6P7pGz66VmYUYI13FdTPtGZZ8DoXMS6quAbKU=,iv:c/1qJbFaxsd8gWi3zip18tZZqe2KSr36W9WlWQPC5kc=,tag:9lctiWWt7jK+Lxf+LBDVlw==,type:str]
    version: 3.13.3
