apiVersion: v1
kind: Secret
metadata:
    name: itsaplan-api-tunnel-token
    namespace: itsaplan
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TX3BnzO8ydlhouUfQbUNAizTdfrKa/q7oFELb/1NB+QMI9XFTD2Hyfr4SM9Ao5s9V2CaUPl8vqIxTnTvjgJ7gStSbTLMokrJIseBpgPcNUAcrTkkogHGuz8TJuqJXJ1OyyBMJe1D6z0+XwGEABpfr8/xiLvTodPS2xh9uXB7gtGbs8uO1Sddq2gvKarZryu18yksUtrlDEYinpYQZyQUp+cTYCfyqCr12l9iZpiUm12PR4G6TpGKGw==,iv:2Vw4k6W7toxUBUf3VnI8tzUtDlWNH1RnSJvd/KZqS6c=,tag:8p6qV5w3EFFl5TvK1c5EyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM3V1RVRTNW5NQ1ZuNnFr
            THNMekt5ZUVBY0V6S0hHRC92Y1pHZFdRUlR3Ckd4TVJTOENmZU5qVGF3VnpWc2gv
            QVU5eWJtS2JNWmh0QUY5elN0dWkva3cKLS0tIGFlTFp6MDhISzBvWDA3TDdEejBY
            VXlzeW9TeVZBaW1hcURNWUMzNnNaZVkKqn3/pQQAq9ZAvRha+hRRLqhb2FLIstkX
            e0xe6MWz6iQhb1bRrWvZVYoHZz4f4B0KvgelC8NJrjzgnsrsyHtR+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T20:59:26Z"
    mac: ENC[AES256_GCM,data:iTZIq7EJt1CCxqinV97D2tn2rcHDoRN2urrHKHCw+EKyydN8Lv6YmG+uIQD4IpkHNsYwuSrxsSExkeFieW1rHWU0fZrMEo3Afo8AyIFNy3zc6XmoTgZkon+tgdVdWsnz+hP4C4XwqQeyP+UfCU6ALkjRCwJOahLHlhrrX5UpTdQ=,iv:3elnLi5mWR6cRuOz8BF2VuusG9s1r3+IjrJJRCmiS2s=,tag:gQ+s8t145dRi6rvnwdqa0Q==,type:str]
    version: 3.13.3
