apiVersion: v1
kind: Secret
metadata:
    name: itsaplan-andrzej-webhook-creds
    namespace: itsaplan
type: Opaque
stringData:
    WEBHOOK_URL: ENC[AES256_GCM,data:njHFlRPhV8xL7TCgWAT7NlAo1X+95tBrwMMpcZJTf2qkj5g56UrsbAdPaSo4K67lqje3,iv:9N0Z4Uv1F+ZWqxej0bOKRvEv+9RwZaPOxeL0vEg1P/g=,tag:Z+kqcj6qXW18aq0HNZX6tw==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:peWquOhHjYZ49S86YWKhTLALSnWXZqxqGpu3IQgiqFKtN2h5Cn3X/xeJdQ==,iv:Jc1ldS7XjbZCviJZU/sMjX6pllKtX2gMoRv43CPZmuU=,tag:Ad66Vv0t91f7N8AVqccggg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMEh6RFZjNEpQTk9rZHN1
            aWF4TER6NGtQdWZ6T2hlcEZlTE5ybm1rRkRnCnZnWWxyRk9nOHNDcG16dktpWDdm
            QVlOWThlZTZGQ2hYNnlwU3dsUTJIZkEKLS0tIEkzRGtMdTJDcHkwRlVUUDN6cUF4
            U0hYNjMwdkVUa2VZeWNSVmNUejBRUGsKGq3Ouadwv+rEgnPPC55KmSEoBB7vyR9F
            t/zj8kVbvyyUEKERoqkmkBnbbJOrzesfclOil9gT8SYY7qemMBiCNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T19:59:35Z"
    mac: ENC[AES256_GCM,data:Zc+YoaISMSOzLmKr+4k9gxSsakbAh+7Od6b7kjHPqPzMESx8KZKOUBQcFf9lExNz1xPFtNR3kYKfsMR1Xt9VuAdSXKbogJom4LHOnYzt8cb+QUDvXMejpDRi6ahQVFYZpe44ILSqVLVbh3feZrcFDFxo+CMGV7ABPGt1e+NdyJI=,iv:5qnkhCrgyVwyKk+DpNDXLspfEWex6xPU+DnUUxw7gR0=,tag:L3KLd+8ETG/SzQKg429s/g==,type:str]
    version: 3.13.1
