apiVersion: v1
kind: Secret
metadata:
    name: grafana-tunnel-token
    namespace: observability
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pDTTW5bEhTc2XDN033gDL5bpFPQC2lb36hHRFkgSjRCOJ6VHa+wV94Gs7HOnwFVe98CYuJfNL1uEjVDuv9TXeH7xL3mA2YGuSvy7mUcrK/nCFmHpvx5yAVCP7DvjacSvquRXM6DlfoXa/wYj1RL5+AN6ax2pQIE+vUiIJnWoANPGPErVqDxLIH/xoeRPcoFNxZikKqiX/UK8dmTInaU8PBN3WIXkUIw1szTeyvA4pZuwjhzQbByIzQ==,iv:DdJ9bS6/SevxkBTPqFdeapifgRhrEhxIHFBLVCIu/ZY=,tag:+ZmHbqH1Avzrupo5OvJbJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UVMrS2FGK1Nqb0QxZTZh
            Q2JIRFlVMU5QRWJUN2t4V2ZwcmFQV2x2UUJ3ClpNUjNjN3ZQVmNZQythZ3lhcVE4
            VWpPU0FZUnVMVDE2M0Y0TkE4OUhMY3cKLS0tIDkwSzZmYjhvV3FLTWtSR2ltZmFY
            NUxPK2FCQy9ueEVkOGRvK0FkaHYvc1EKzZth4I8sOjahMHagluS5GYj8rL/eBbRQ
            jnQ2iclLt6ZctUwtuu42Bk6hocN39If0Z8E3wq+rB6Oed55tO4xCLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T15:51:12Z"
    mac: ENC[AES256_GCM,data:p4TJlEezZsGL3L3H2j4cGha43pVr3TtoaqwdMuFymm91i4kYDQu/qHF/6XPWSFHq+oVv6BgluqYJpmOTnYv2jqKMCF6PMbtb7tBXWV+2zsaso4fKUogfuoPB9ha9hvQGFFISd6Xzwj8znLNkCgcpN81XjeeyLc4+c2AtzvJBhLM=,iv:Bn8MK/6AParSxfQLLdD7F8D0w/EAPq2ipQ8Y5ImQZLI=,tag:iFqL/iTJ5/dObDX5ngq42g==,type:str]
    version: 3.13.1
