apiVersion: v1
kind: Secret
metadata:
    name: grafana-tunnel-token
    namespace: observability
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:K0U1xbkieu4fmXRMmoeXR1+JozcO1Wt39wa39U2kob2NWD1cmSBRqDSsOHtQUz/SRC1rWgOzzYbGuVOS3AtvOd0zs+C+TShbt5IHA8KRWx7eG8967Mjk4uMENkL7t7VqC4oV4fX+zkaRAYL/eE+eK9Z6V/cMXiTywc2GSSEfydYUS6L3Rj02+3lwwUZ/VA4Lx1DKCIZQajWxj5U7raAK2aCKFHIN9nKs5RrYMxT+HvX/NSbvVWBhyA==,iv:FuIlnfk4X0hqarkHJFIOznv/UIR0jbNWDrrZKwinQDg=,tag:F+20HTd0CtAsP3tpLKFWzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvamlNSXVtZDRSSGlNRExD
            SzhUdmVzeE1jTGx2NFpjZW5EZnBlU254UkRnCkdaRnZ2bkEzc01rOXhJTDkwdk9l
            dFowdC9ka1ZBMHUxYytVbGZNcTJucEUKLS0tIGthYXRkN3E5RklMdjZCb2Jscitr
            SmN0elUrQVhQSUUzak1ZRml4bTRXNmsKStVCriqfjX6EO0VcQXDxRY1tstDu/RkQ
            vbRLeqvifveDyUSVovbEtAAd6BZEi8FUQchvQR52zLGSv7c0OOQx7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T15:50:03Z"
    mac: ENC[AES256_GCM,data:ijvD+cGAalF0zRu1pNV144cawhO/D/ieVJHkb1a3Ffw+o1jSs6RqRVp2G8Be5f5OXEdi9Q8wtaND2afwxzpYnIalkTBZpZHLRktWvpKdy2Pbg58hmOxZYLcPolEMvnCvQ5OswK4zx2YKhGnJzi1rU0GcCi80NanHg2RrplmPzrM=,iv:xt36laFyVRyW8Ixz0bpzPpoDUTTdvxoI1lgOwdAzI+s=,tag:967aQWYUNpd0yU+AfHrP5Q==,type:str]
    version: 3.13.1
