apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
stringData:
    admin-password: ENC[AES256_GCM,data:ulJSQPa9mGAXcU94U42BOlE6CPjLDIPTK5Se+eaZav8=,iv:WHqvbZoJU7KtaBBpOl3ERZTRK9S8GTYHBaChbt7gM9w=,tag:zYvxiOHX1UTAgxfMBvJ7rQ==,type:str]
    admin-user: ENC[AES256_GCM,data:VWt1m+E=,iv:EO/X3x47me9elvC0JXrM7qHJ37GKAZdo1eUlIDRBg6Q=,tag:1qzVjQ6sjgqGfJ32qf99mA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQWQvV1ZXRTBtMUJlVFFu
            bmx3WHFtRStOMUVxZ2lUMTFqenVvVFBidXdJCldDOWlucmhYTnlva0RqaEdJbmdW
            OU5VS2Z2T3A4YlRmVGVIbVQzeG92N28KLS0tIEFtYUV4L3kxeGUwWVA2Q3o3RjM1
            aWVLa0laZnhaWEs4ZGlmOGwvVnU3ZXcKiMLKCOW9YG6nK2NHC3VN7ow5LysI1scz
            kiU0wTWzrG8CWO15lYPUFjFoc/OpQw9TYCzwAPe8wdJRkPnGrHlazQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:25:00Z"
    mac: ENC[AES256_GCM,data:IW/tdUsd2qVtwUBCiAtSSVDBM5JiJxxXaVxdPBn1hBhJNEsh0oo39T/5bVx7t0rY/ard92ZnoeWgG/zCFuX7K9ZvO5UKwB7xljMoQmLsUdKTtK8oarTi5X6w1Due7joigm7tXMFoxCMlIJLbCS5viIIt/VsDJJRZLo++9nTzEdo=,iv:j8DUyIKJckEtcny+qxnuo6EGNCjUieMcxXCHp6XWMiE=,tag:yNevv+3pTgUUC1HUeQUnKg==,type:str]
    version: 3.13.1
