apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:KhyDpCM=,iv:SPMUvSkV+1xXEjPq/geKE+zh+0LflBdELT5exJrHuL8=,tag:not/SWOIsmW7ISmVohCjXQ==,type:str]
    admin-password: ENC[AES256_GCM,data:CMFXg8zjGLMwthqn0lCEsf8o8MynnXCnzcMN,iv:AW8TH/K0SZ9uoUutn7GvRs15XZxxXD9eWNZ4qv0jU5A=,tag:dNzZrOBag83zsFjFhf2WaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub1V0djJvZ016eG5pL1g2
            eTVCT3RiUlBpVzAwQWt5LzBIYWFQaHN0OEM0CksxWnNscjVvaGNnbG5IRnA1WS91
            aVZaQkxYZ241NUxLQU9BSUFucVVaTTQKLS0tIG95Qk9ROGh5Umh5ajFndm9xZ3pO
            NTk5NDFZTmkwelVmQTVHTU5NcDhFYWMKc0tnJoQCrtnYbxjqUd1s6+lMkayaoyRh
            VQTOdkHL/8bOmGor714jWpXMUUrsDLiyZiul22Ln0Edhd0e2buobKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T15:13:47Z"
    mac: ENC[AES256_GCM,data:y8RrFxLVoz9fuB6WKAv8wIdY49OqAcT9rgtv8BtfeSBv4pmBHyF4d7PqERLUXRHEeb9Qx3afwn8MiTy92n4vdlC3FvY/SBHVWTSQhW+T7B8+7wOuiUytP+pV9Jlycr/cdMNjUvHbTWzBTMJVe7Wj8pnODCVoyvezwTikr1M528c=,iv:dDz0heIDcuFVzsnE+NJbpZNfOMXgCfTAjYyw9i09nRc=,tag:aYd9j2qT3VQ7/YUfEk9d9w==,type:str]
    version: 3.13.1
