apiVersion: v1
data:
  url: aHR0cHM6Ly9jaGF0LnZvaXRlY2guZGV2L2hvb2tzLzN5OW14YjE3NnRmNm15Ym9xb2h1NTk5czZh
kind: Secret
metadata:
  name: homelab-node-mattermost-webhook-url
  namespace: observability
type: Opaque
