---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-media
  namespace: arr-stack
spec:
  capacity:
    storage: 4000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: openmediavault.local
    path: /srv/dev-disk-by-uuid-cda9bf6e-0ed1-4e61-b063-1cbab7351886/media
  mountOptions:
    - hard
    - intr
    - nconnect=8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-media
  namespace: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4000Gi
  volumeName: arr-stack-media
