apiVersion: v1
kind: Secret
metadata:
    name: arr-stack-api-keys
    namespace: arr-stack
type: Opaque
stringData:
    sonarr-api-key: ENC[AES256_GCM,data:h+8KZOQ9Cv88ri+pG6Z/3bhJvASq3bbgk+mCniFsZ58=,iv:K95wcXdCb5gHXxwrKa/6GuqykSP24HSf1/NCFQWy398=,tag:Ts1s3J6DZPvyAFrDKnZkuQ==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:XyKpW32Y/aBUQhJMFT2UPCsQCjLaZbzS2C8FMYqDH/g=,iv:/Y/3oDg/r/le+gViekMJkH1c+7bblDxqE2XsI66xjRY=,tag:Yd8Ij15px6Tjcwf8vm6+dw==,type:str]
    prowlarr-api-key: ENC[AES256_GCM,data:w0MF2hCMXpAf4lzAS9+xtU84iwK8YxM3mYb7VN8cSvQ=,iv:CSpGeOzyHn6ZBe1SlWdZVU6j32r2X241Gn9oew4O/U0=,tag:yd/kjHnF2HsLLsGwwLVlrQ==,type:str]
    bazarr-api-key: ENC[AES256_GCM,data:COY9dUFV/Rat4tWvKeyjGUNUHL/dwgc33YC7di9XEcw=,iv:IIh2Drris8OwBexUxRejY3kBkYIwYuflW4+me9VozWs=,tag:iUXkGzXEQM9gMlUoWoj5tg==,type:str]
    jellyfin-api-key: ENC[AES256_GCM,data:1FOu6jK0w/xWDAV2ameOjg4Jw2RoVovJPDd9+MzvymI=,iv:UNbCVa6n56XP1wYTmyiHETEdtuVT1wQvVf4si8l8GV8=,tag:KNKvLOKB2bclXXPmHpjQqg==,type:str]
    qbittorrent-password: ENC[AES256_GCM,data:Ydx//js0B/ADRO7kVll0xw==,iv:jnrvwLdzK+HJNiZMSGxD908k+uTzdvLEoOxfqg4J9Us=,tag:bEX773IR/TtOlRr/b0JIVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RW8zSHBFZEJlRllXMmdE
            ZzNWWGRRVHVpUVVZZnJvdVgrdDcwak4wTFdnCmxCSHRzSTJvOG5sZ1hYVUpNNjZ2
            V2w3OVZpTFRkaytYTmpNeVhkVWxYOVUKLS0tIEZncWFlbFptdXA2KzQ3SlFTMDA1
            ZDY2VHAxc085NTZwaUtVRXFmdEkyWjgKokxaqh37D4zt0O8zY2U1KJYwFQ/HI4x8
            IQpUesr2sRK7TH4dyYuunEGmimJ/N00umauBN/KnQI8GbcHNFg9y1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T17:51:21Z"
    mac: ENC[AES256_GCM,data:S7lX3v18mmWh0MYFKYVQBfym6bCLOzuXaCzrsJewleccRIsMTcikq0OomNwJJrKT9x5+OOlDpVyNFuM3X/ILDfXVjlVK775Nf7VRIAylKIrL7uSt5LlkXtRyRX3p6PYyh3AP6Mto5i4ZgZenxDXyh7mdkgRlmgMGweRbcH63znA=,iv:PKVYwxKNtO0CtbVNzamLUbS+FV7Il7GKc9Nnu2fr3ms=,tag:RKUrOkXJxGKHxzfs+yCSVQ==,type:str]
    version: 3.13.1
