apiVersion: ENC[AES256_GCM,data:7uM=,iv:2LVLHweK9iHxlStY2uRg6lBTkjKUCgTX9I9lkBWhY9Q=,tag:UxQgrwNybXj3tVLmQSjRzw==,type:str]
kind: ENC[AES256_GCM,data:tAP1isZk,iv:ZKiMDdJWT091O43DjJv1DoO686ndDV5bCs4g3WJaFLQ=,tag:xh9qEbms7WJFNdrq2bzhiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V9vWsvYzJUf1nl1UIe5Q021iiO3eRwDTOnNY,iv:PYnpiRBbKG2flVHwCU6kCHx2bk9f4l4ivPiVJrVIn4A=,tag:6Sa8Es050dJu4KpMKyCmyw==,type:str]
    namespace: ENC[AES256_GCM,data:qNPvYOpZ6Whp,iv:R6WlIKXJhQHIN38bV3Q9EybjTkQAFR/wLAHyckvyP9c=,tag:BEY1EF4lUTCqr48whTIPdQ==,type:str]
type: ENC[AES256_GCM,data:h8OvOp3p,iv:N175HixeEHRPRIdM1vsE+XmqZ18WfXQR/93Bi5cczIs=,tag:EmVIcc0nJodRG5UbJeqscA==,type:str]
stringData:
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:gfBF1KM=,iv:YBORXyThExP2dwJ+pYSakG/8JF/NwDP2Ug2dWe4JtJg=,tag:1j5gOQb4NAgRO1c+sAG38A==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:GJ6pyiAGPkBKXKDCyDmtno6S/mZwESm+,iv:Js4OJ+6+/fsqexpitasyFGlWUomCUtFg3+72mRxxxtI=,tag:D9sKZvusQQtEIWuxFHlyPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSC9DaVg5TTlrcnNSWlhs
            T3JyU3JkanQzZDJMYkdXckNEbG1CM1dlQmtZClI3QnJLZ05YeGpqUzlmeS9WWS90
            MUI3YmFJdTRIRzFRS0V4c0VoS25xTFkKLS0tIDlhR3R6b1llUDhrZjNKUlNVQi9E
            NVdiRjBjRTdLNkJ5UjJFUmF5b1U2RE0KTVemXlvSuKq2tB0fKi22dOdh/+bNG104
            GEFhwJj8Ojgfhtg1adSv+8Jb5joxFayrJ5VKBc26EIvKdq5A6q/F8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    lastmodified: "2026-06-21T20:24:13Z"
    mac: ENC[AES256_GCM,data:eN9SCiFSHPEJMxL0kE2J39kutchTVWKO9wwK3GTzJtfDDDdM3/lIG3Xn3PBBr8QHCjwFzKx+Vz3G0hX2gC1Xzo3QXZ8maisJepPULrJ+wmKlqNLoYxUeXxPwBPPXkJW1ye2NZYQJf2HGHoPlWB/52GrYcEXhvQTUsF4YfXh3DvY=,iv:fuFeodRWhHejRSp9e1yJvhRceBygej29MlIT5LQMKv0=,tag:p+mbl5lfW2IG7L2haTLFmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
