apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin-credentials
    namespace: nextcloud
stringData:
    nextcloud-password: ENC[AES256_GCM,data:RtqDblyaproB9SQ2j1fdTzHAsAKsQ02Bq1e1N0IVkAI=,iv:wViNpmpLVTh+9CL63YKO+av3AlGDNIsHcW64qQnrnjk=,tag:b6Vo0G1YfOgngetIDg1djg==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:NONIF5M=,iv:EN7rA2edB+TTcNh8NZAnHGY2xNFMt/aKobxhBALeIjM=,tag:BxnaN5h9YL+i3wVYwtiAkA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtanBGVUJuU3J0YjMxQTN3
            RndEM21KZHowcWg2RlVDMWJ5VW83T3hHM0hFClZtUFRYL3VFV0c5Zm1zbklhR2s1
            b1ZZeFB6VjREZTNJV1FsK0Mrb0tqSVUKLS0tIG5pS2Q3RThVLzA5VHpIeUQ1clAw
            emIwQ2MvWW5IcXJyYXdTaWxiYkNSZVUKGxT8vt3THmJJ/EQR/pGIMmNoYC4qQ9yQ
            Lj1ancekQJLtA+tgI/JU/M2jcHQgqjAmhzlWUG1D+iRWYGp01Y4uhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T05:17:40Z"
    mac: ENC[AES256_GCM,data:wFtsLHvsLSr8nPXa2mKrDlkeD3cjHBfI0oSFRiSJi9nuRKprFQEk+YLSV4lKILIGlDvLmuTBrRIJZjuy4O4yTv8swr9t0A5h1gpC3Z1SF0zvRCFcw5gXbeL6bDG5J42GMGvd+p/Pai3np7XLoLM2Ib9P/9coIIrvlSbbNTdWMAw=,iv:TBWyHHYzz0G1nfPqLorIIDJyYpizorshnmFvgnCzgNo=,tag:CMWzIzagObtysPQG1v+87w==,type:str]
    version: 3.13.1
