apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-minio-creds
    namespace: nextcloud
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:JPB/D1BKs7h5,iv:9qvcM5aUEg+Bx342gqS71se+14lKICStc1MBWcti3zY=,tag:x7OaFv7xz1VVnW8oZ9F2HQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:VnDe2IygKk2QNnqePe00fC2ZgftdFdAyqxh03w==,iv:1AXn7ONCo/vOt6Uim6OPp+B1/kQHFd07Ff8SbRLBxaA=,tag:fbLZOSMe7m7zNWyvO3diKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRWVkYnZBNS8wOW5ZR0xT
            NXFBc1hRcFQ1cHFNL0tNcDFZT1l5RWtmaEVnCmRRbkxJL3llNkpUbStLRWFDRDJx
            ckNqaXI2QmpvUjZUNW5QaWxXZGpLTGcKLS0tIFoxZzI0cmRkdEZKdllBNVVtMHBi
            UzA1dVJPYk5OWG5xcWZyRW5jK09IZkUK3SOr7wdnY5MB+NflbkkuNcntOf5JX3RL
            eG2rNrXJnw++kpj4ex9Yi4UA+GPAuZZrxAHmlztCd9lJrik52X0+Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T22:33:46Z"
    mac: ENC[AES256_GCM,data:n9jnweBWO5KvTbJY11cRY4GFwWTaxdebVzeOZVuwtqqETn5bBErKvMxP0MSp1cPzLzIuhXjRTSl4dI5NkdABTflVG/77021uyl3L2KYrCJ/5UNSlvmHWbF5AuYybcyaabCOXYXFkOY4OqHaQt5/AckxejZEeLROs7+1VIA01M7A=,iv:4khhzlQc9CGlDJ7kKWQspYhOTclbfD3HX587sxSW93w=,tag:q+y5cxtZTOQTMHmB3mhM7A==,type:str]
    version: 3.13.1
