---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-db-daily
  namespace: nextcloud
spec:
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: nextcloud-db
