apiVersion: v1
kind: Secret
metadata:
    name: karakeep-app-secrets
    namespace: karakeep
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:7HbmE43ow3paJ+9akjek7KWKDsqocmPid8F4oUEKx2cN1f/cJmsDZRUbkpYSWJFN,iv:2/cnY13G6wdBbYFFo1fvaZGgMKDzhILJynrShBOtOQc=,tag:wcASsGqSdqHcqS2/AIvQVg==,type:str]
    meili-master-key: ENC[AES256_GCM,data:k7uXeq8QyKWMUxFmO+504XVpXfUPGGoJ76uw0Z8G9RI=,iv:iM6lm76XBR0oXINkKcc/g695ub6yt4d2BtQNzl3g1NU=,tag:93wEpMN3eY3cIroGPrRPEQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:6EDdl63TN8/RUfqKAZNJoYqSnSadRWtksmqGLDQb8pA=,iv:f34sOi5Gqmb/FHvlbTZ3yQdNZZRjA8G6vPLMj99n2N4=,tag:GIAsanxvSnPogC/+ZzYk8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SEVIMFdmdnpBbWd2ZkxW
            Unc2ZzZxNW1keE4rVUNIZVFzZEpPMEtrWWw4CkhKeFJaNlZCNi9FNktZYzhPQWRD
            VmhVY09DK2N0c0tRTnE1SXdGbHRYRXcKLS0tIEpMamdjWEd1K1lDa0pIbmREUlU5
            bjVVbDBsd1ZqSXVUNitXVjFtakFlMlkKdehJW0yvg9oYAiTGPsMhdBot1htXCcri
            OAJmWRU69L6GxWsVCwn4vY3bvUjBLKHhvTNdgG9mXrFwdvJLk6AYlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T12:06:42Z"
    mac: ENC[AES256_GCM,data:e0ATIubUjjnWPYx8hsQpcmK9e5r/o44WsI8Q/ynYblyofioRewqE9RWdX39/oX6Fe2+zIxKCKqoTWy30kEgeleVJdeOAs2Meg2PVJvZ6nJ9X3eII//8mqQzqG66m7tMMDuRqf7L4gUqBrETY05I1PcXMpMh4GaNNnv7Zis+taVA=,iv:UhYxkICFd7TDmf+vt5qCzI5IKqmQnGavuo/sMRlqZaQ=,tag:QBkUd5OokD0/TJvYtu23TA==,type:str]
    version: 3.13.1
