---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: karakeep-data
  namespace: karakeep
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: openmediavault.local
    path: /srv/dev-disk-by-uuid-cda9bf6e-0ed1-4e61-b063-1cbab7351886/karakeep/data
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - intr
    - nconnect=8
