apiVersion: v1
kind: Secret
metadata:
    name: karakeep-app-secrets
    namespace: karakeep
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:DpEhq8i592VIzYlZOFRaNsV620FWX5wOi10jFSZrYlD9ZY031nHCS/T264oQ1zB5,iv:/q8oqms7wuDzcMf/RVX266nh0Wb+23oaZa/zuE5aqEQ=,tag:IY2JwzwY3yzkBDFOL3U8Sg==,type:str]
    meili-master-key: ENC[AES256_GCM,data:nOEEA4vwSegkCQCkymh0GFDJD85ivOu/rbrGnJlSXLk=,iv:BJuOBkNsTcprwfvaBVeToFA/T9PEmwotcERG9R0Z8fs=,tag:qm2AuqpbXPVI/11GRIOx4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHRmV2tIKzFxbCtYZU5X
            RFBoSktXYnYwcHZTaytJRFJIMVc0ZXlrSlc0CktrQjIxdlFIaGozTmlmTU5mQzNX
            Q1VZM1FiQ1pzUmkvQ0pPcWo0QUpKSjAKLS0tIFVSY29PaXcxWDJXV3NmbC96UWV4
            QVhXenRNU1pHSm1xcWpCMkY0aWs1V2MKYFRP+JktQwNyafo2t/+/nGflmGbxlBp6
            2+yK3dAXBdYli5U3hHNIp+XdYJZ193ocq/JXUJFpliFg/PbawAe15w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T11:45:30Z"
    mac: ENC[AES256_GCM,data:LjcnBCH+QkF4FEEoZKOUOsjG7s9N8G+1/pfCD0Phx3pWmwPi1csqotQk8lv+9t+AZsjP77MwgKXtsfnb0ZDT7lMz00yILgf7Jzt5GTb0gTZoluejN4ztrBaHgPjM04ku9qFXTRZ6ZW6mzAHNEpYbyEtJfzmtX+xWC1MdLDIOWRo=,iv:1QY0MDzOQdRCTpQ/TIQojvdjFt/Mp883WFoee4EwiFc=,tag:3xDD6LD3Swm1a4iCnVAdAA==,type:str]
    version: 3.13.1
