apiVersion: v1
kind: Secret
metadata:
    name: karakeep-minio-assets
    namespace: karakeep
type: Opaque
stringData:
    ASSET_STORE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:S+/WX0SHPKrcqIx0/4XIbI5pO10=,iv:RrdAZSoVPeF6zx0o8fCH/loJk/mB8KEG5SOBukB8V/4=,tag:bDXMjXb2ELOVdaLpZhgDMA==,type:str]
    ASSET_STORE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jaPGVcIS3uH/o0peHm3Os8MwYukr53phNkF5HYlan25lKhPM0hiJyA==,iv:Bp3iuRZakKabpr8M+3tKemkMFy7VzQdsydKrCOPHxJ8=,tag:aJOXdRzYPuMQl0mKmDppSw==,type:str]
    ASSET_STORE_S3_ENDPOINT: ENC[AES256_GCM,data:pKup4TBojjSNF1BoecnKnyv8h9HNIh5eDaDUTqG3t6g=,iv:7BHoRMXnGfGgtg8541tBagiCG0yQ2phfrl1wcVmeexw=,tag:SOW+DwaA5IX/e/O689zjcQ==,type:str]
    ASSET_STORE_S3_BUCKET: ENC[AES256_GCM,data:clOaAJk4BIyt4JN5GvvZ,iv:kljd6Dsczx+J1XTJZ3AZBx0pL4f+qenAOteKcOPfV6s=,tag:A8DedawsDiBhMYcPrQJb6Q==,type:str]
    ASSET_STORE_S3_REGION: ENC[AES256_GCM,data:sC+r9Ig/LT2X,iv:/jCPWsKtlducUo3uJtFJfvgI731tFag+pdXJNEoyrKg=,tag:RkVQugpJXy7KsaDjr+Ztsw==,type:str]
    ASSET_STORE_S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:IDaEDw==,iv:+MoWaKcWpkzMReK+p+k2duJjVc9322O8dDsXqK7HvzA=,tag:0uOECLy+Zby2KrMv/Cg6og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SG1VQ0VRMVBLSjNQdTNj
            OHpqS1BhTHR5VWhzbTV2NWVSOWIvT0lGTmpjCmp0RE5iMWRjVytkSmlBWmovWlZJ
            Z3hHcHRJTEJqVFNZYlJpQ2V2ZHlZakkKLS0tIGRVbjU1SEFsN05VaXJPNEN6Vk9W
            YkRGbHhyWFVrQmtlZ0JYTGg1VzNWbjgKJx37iig+mtn0T3TZnOzC1/q1sgdl33O4
            l3ZQX9ArgXNgRURgX6mr+ciwfdccOCzied49A95EUnneh5DvGBoppw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T12:43:01Z"
    mac: ENC[AES256_GCM,data:PiYRyVCBHpXfKjaav1LPRDMxSc8EPgZkG4gInqtXRw2Gtlik6ArIRSnytdU9q2myc1bTb+1qQXbHD/eM09Z+txCrjcF7Lj5hRxIT1C6JtpuBR/XfViPNHtGQ4J98d2fgMeLI55ZTuyMHeBx/3+o0O9ZhqmtfgQuDKxLCvS9YXfI=,iv:GaXd9daSHByDSWdYCYW33CbzONbbd54BquuZbmGxUa0=,tag:W1VZJp5WZqM567kRPIo6TA==,type:str]
    version: 3.13.1
