apiVersion: v1
kind: Secret
metadata:
    name: karakeep-oidc-client
    namespace: karakeep
type: Opaque
stringData:
    issuer: ENC[AES256_GCM,data:wSmnf8tR1lxGvNGWfS1zNVOMW/4rob6jFD0wmfybXFbWJMWCCxGUWPnnK/bTR34=,iv:ryNCGYPndYIasXQGus6s0/7Z70XkJi58xNLa9zFeY+k=,tag:aRPZ72O30wP+hgSKrMmlew==,type:str]
    authorization_endpoint: ENC[AES256_GCM,data:UjFaqVJhup10CLZOr5STVgQcp2N5d6Jd2v92U/K9YRddqKMNUv5gncP26ehCiwgV4g==,iv:nuFCJhPNgzHG3CKRKI1OqlHziLOVCb2LjAuU8bV4AYo=,tag:8iqLMgNB2t31pvygK5bTSQ==,type:str]
    token_endpoint: ENC[AES256_GCM,data:lo4QXOtXCHWvU2mEv0sTeIVQs4Oo5HSrdyQ5vdD92PcikO9SamE5b3YyhDJ7,iv:oXMaYw8rcvWxcOCmkpVe5VIp6JQEdkw/1s+r69GQy6c=,tag:uSoRyeW4kt2aVF7VxLw9rQ==,type:str]
    userinfo_endpoint: ENC[AES256_GCM,data:fmHYRkuWp6YpCwUquFgnwiAUEo/mRBIpTsPphf2WNW+JKmWYq0Dk2aBeK36QvTPC,iv:KCtnsJmVy9WO+xztfUeD+BlXG0noGy6eTKbFE2WTkc8=,tag:COKueha4uZKhxJ7r0wCDCg==,type:str]
    end_session_endpoint: ENC[AES256_GCM,data:kopHJOdV2Nvz/SCji0VxzL4MieKv7ppBD5tBLi/Vm9+JxFXvxohC6Ln3tzVBBXSKgZNi7WOoJmXnjQz5,iv:17fZPo2lP53/TqPBeDrBmo3kr626593HanImxHVi06Q=,tag:1XhJsVdHCrC0L9/6Gv8xsg==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:evBNYRlewWE9xk6KOUTTD5iVnyNI/NQw8w42dy11eqOnVjEAlnXz9A==,iv:F7XMrZtPAK/bxxt8HKYnJgknJ2UKDNxNaQ/UyMnQed0=,tag:PIaZwCxsysD5E7z/nqgg0Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Ieg4PF6hvXO2Xx+DLT0W9d3s8ME1RZ+yaa2RkmX2jFAjcndqdiHY6mBRCMYjw0+KMFo9zsLKyp7YKniC,iv:NyyDVcE+cDglkbwNZ9Kn93cLKSMJe4e7F69iNlYBFAs=,tag:CPTjHdeybklbK98j/7EIPw==,type:str]
    redirect_uri: ENC[AES256_GCM,data:WAcVxtxfP3aaTk/59UJERfrpnTucenFaIoDJvXWmfpyRlmIY7rhO1m8MKxb1Y9TzUA==,iv:Kfwd3O5c9SsD0SrIaoMpmlPO7YufLZzukisESbLsDzU=,tag:nE6SrkYlSmOXFU0xpTGRUQ==,type:str]
    scopes: ENC[AES256_GCM,data:i2oK/JJm4G+l0ILyAXZ4k2dcII0=,iv:kA+C7nurl3A3WwcBcqtilt2bUYDankTpSIYMiVx+j24=,tag:4gPWBaoy5N6b9o56cyLJ4g==,type:str]
    provider_name: ENC[AES256_GCM,data:qMlb7aJ45yTv,iv:I+Ue/FF7599r0y5rGq+9puiqwPTOvwjrmSfca/Mcifo=,tag:3QHRSXCQVs2c8Tkx+9ap0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQUpRVWVUYXV1ay9jdkJw
            aVd4Q1NmTDdTSnBnQ0s3YXpyV0R2UUtpSGdJCmdFeXB5dUcxWEVUUjdRanAvQ2Rj
            c3ZkSXRFb2lnaVFmM3JONk9zNE1qb2sKLS0tIDZrOVBkazZWdkg1eHFJZ0p3cWQy
            N3Q0VjlLQmN5TXFlcnVYSDRxS3B2ZU0KrEsufIIM2N3ZzKYG3JWPS/fmVjqKu2Fg
            fPPLYDRlTUM7IznxG649+Lx13k9UJVHRZd7NfYZMwqt3qu3eTRRelw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T17:23:50Z"
    mac: ENC[AES256_GCM,data:zlJqvgfoCdgUm9Qo685Pa6B+KqgWHf3u+RwD2u8yPY833c1bAKm4Mnw1jZD/TRmp8SBFYqfqrTkx+ot19V59/zN/yeaXJv8o44XKMM/IY/Puy2LUgFCyMt2KoqwBLzX06MNwFCUMMyCVv/SHWMHtyM7DuZtFZAOuIkkumcfyZiQ=,iv:nnT6kRsR5mDDhBaKTP8AcvzE+p7iaUjUjY8WBVkTFiM=,tag:kXaC0QFwky+U2hgKy1MRFg==,type:str]
    version: 3.13.3
