apiVersion: v1
kind: Secret
metadata:
    name: karakeep-app-secrets
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:NDXe60uQRzWiWBa3vhZht6PjI3KNNLxvLbkFjU+qnFMOXMlvQx96A9Ca3OVJs+b7,iv:fkDOxJJNRIpjbby3fVOzrkIttSngziE/kdErYcz8WFw=,tag:iZTjjTWR2+6G7lIZmDx2ig==,type:str]
    meili-master-key: ENC[AES256_GCM,data:n+C4x8IOnPfepqhXyf4MK9anUI53efZIm6aHd9GrKOY=,iv:z7vpNPbqf/zcdDYGazMHlUJhauSDN7fz2RBWfSoVmQg=,tag:yaG+RIUqHIVAv76uJq0sOw==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:CRaiEVq+2fMXuONK+wbn74N9YQuFRA1OxcYo5obLYKs=,iv:w8yMkani1Jap5Qhgh4PT8S42jJ61+JXmcjKUZNcf8t4=,tag:kcWWUc3DNQN64WqKuTAH4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU3QzZE1KUVRmcEkwZ3F1
            QTI0Um05cXZ0UUw3QmR2RlhmeHU4RE1GQkJFCmhRdENSNFBnODBWcDRNaVFQcUhy
            MDBsTzNJbU4zLy96dG1VRFlxYlpCTFUKLS0tIHB4WXB1Z0N6NUVYVmJ2T2RGYWlY
            TnQya3BnUlJFT0VwSXliQ3lHUjJzUTAKocdy0cTsdepnVTIaWL2R+kYO3tvWBvaC
            MNastzCiN8Egks+1S+UZfrxSaXZw2II1ZqV7rm26ju6x/s8IlP/Wow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T13:27:48Z"
    mac: ENC[AES256_GCM,data:AEDbFsCijS6QBskH1XYzTs7SvQIhz9QcF/XlDIJSlUXkV7AEnGjQtI3ghhhzX/c7rDmtNKdPx+NogBBHpjEv3VETaJlITuLTHsZUbLeHCS4/8KY8+CngCdNp5v2sKdgM/8froCAJeRYTXDjPsZ2zl9v+DwSksF0PcD+Koxf7flM=,iv:PUg8fEK/48QK4tuWJgRLS1QsaDcHGpeThqKbvKt0Eu4=,tag:KYYQHp4ckEx3R8fnvjsh9Q==,type:str]
    version: 3.13.1
