apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: auth
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:bxKPbuT1ZDNlhn61wivLXlRVgZDr8KimoI9uu33DHD1ZBpJygU81Ep5a5y/5rjJA7pCcNPexQQG/LvvhXikNuA==,iv:rmt4JRHWfzHyClXD0ioPooCa5imSA4vWkdQMz6FAZ78=,tag:g9pOCUOaKLgR5rnaMVg7Hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjREowS3VBUVlzV1lyOENB
            MVhkQno3bGdMY0VCdXdXTHorYjFzTXRldDBZClVIRWp0aUxOZHg5R0ozLy9NOGpi
            azJUWGRVU0xaTnd4T3VyemtmQlIzNVEKLS0tIGhqdDNJVmp5WVYxUWVEejlYU3Ro
            cFQzaFJFdklHR2dISFIwNG40QnR4QnMK4BGKnqUJDL7gzInHk3KacDs03U9eqUhW
            SEu/vwNRPT40dq5+dAVHwwgU1ymKEDPbKJrnD5Sel0lFozeaR4nFNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T09:48:50Z"
    mac: ENC[AES256_GCM,data:0DrqQkUPPVJXg2/uDoNTI1xuzT0SCUOgBSwUsgyMRZ8KMrP5wJVNKqZ/jAj5Cl2I5tj3x5TP7X2xkQ2lSJGbEomi8Ae5NITLO4MUF4qlL00Kw8SbheMBkPH7ESP/NNbdKmHRehgtxCjf6h9gYxCVg8GDHgN7h/QSUGptoWZmeLQ=,iv:2/DwrvVqQWOQ/GrfiwWYIh8kq2XpOicRmTcXkR2tpZ8=,tag:WRMNuWnxJTCIfpVJ+v2KSw==,type:str]
    version: 3.13.1
