apiVersion: v1
kind: Secret
metadata:
    name: auth-tunnel-token
    namespace: auth
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:zm5/exqHn+nBDu9XU/vksGimzKjNijlJX4VvEnZZhpv49e+Rfp2aGvNAERs4vlF89ndUkiB0+GMp9xU1ykq/l0qoIAcFT3MJcm5tJUasvhlFMpQWcEzcLXEsBJPRzzZ3BbgkLA2+GdRJetmLue2d1vdHwmz8+FOQG8qjZ12PsQVt6AVNQ030maNrizVmVa2f1HLrDqrOUmfpxBCu+sTlVGTJrCUVO7L7h6YM55RUc15EgvuEJXc/Ow==,iv:XS03Twt/QiuTPTC0u20jcb2chKppTc2J2mkd+zsqz6w=,tag:H6WVO+Gp5ltt4NkalEHm5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2swYVRtYUl2VUhDSFo1
            T3ZpaUpNSVM1SmtpTmU3OFdxNnpCTHZBZHpJClhBR2FLL2MwZUpHM0k2ZDNxbW50
            cHhoVnJhWk05R0R4Y1dWSkVWeGdURFEKLS0tIDBjUFlLWXNlYUhTam9RNndmc3pD
            V3MwUmJQNCs3dmx5WDJRWk9LMHBlcHMKIORtPRc3NSBnchNy0AYbVSGqiAcvDVeT
            LDfgpxq6ajbiy0b6RyIWZMtFz3MtDGuOkB1D9XubOS0gjDOoZ8VZ7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T10:57:07Z"
    mac: ENC[AES256_GCM,data:MRB9bZ7mVFPQ4Q/06/hpTgpK3WOcDtbqh+qfShbDdTOBfiazKsPk3V+sJrE2iawlQxfqNzoo139sk3ffBVP4r9fWHyQB2/FlG3uFIwNkGiPsfcyrUoXjUD4dv6cfl3ZuZwQAMcmZ2UGDU0+JVd+bUfUYtEVFFps8dwKrIWem/N4=,iv:uKVw0BHrwAdfOyGergQRXtE6R1oSrwCU3lb0dkZeV88=,tag:dmEvb0CsYxGsNyO1A3+oTw==,type:str]
    version: 3.13.1
