apiVersion: v1
kind: Secret
metadata:
    name: authentik-admin-password
    namespace: auth
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:pLgw4ZXqmM9PcOqOcHi1b2gFOfyu87Z2,iv:ku07MURC1yBHYDjf+Ffl2ZLa0CXI2/15+lvL6IjGlyI=,tag:MqH7kdOD/c7AXrBtm6Fs2w==,type:str]
    password_hash: ENC[AES256_GCM,data:HdxVSJBoRajoM3/zPUiSfqwqP/5RM4nq9YQs2b34InfKgKI8dvnB0iQ3u9id3esXitWTxUgrreufhZ9LbuSgR2gexYcLq4ewML9VD/lbBg/1ixrW+SShOLU=,iv:JHHGdizaEiYAlkwli0yjGfPlkpo47tYEldLd8eXZ7sc=,tag:Ry3LjFmOrai8HiyzLN77fA==,type:str]
    email: ENC[AES256_GCM,data:Jyl1eRynCmIl3eieLaVecX4=,iv:eEJBHbGGd2DkVrIELdIlryP1fco+eMu3K9C+m8BZMBU=,tag:z+VchXDrN1ZK8L3ijQlm8Q==,type:str]
    username: ENC[AES256_GCM,data:el3DQUuNQQ==,iv:Ie3kBKYrokZB/CvTURr67GoQpGJbC+z3czqGZBQwwPg=,tag:z4OE+lk+eSDSb7HW0P8yfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISEp2UjMyM1BLcFhUdFpO
            dEZIZGZTMHlQOUhoaldtY1NvZTJmQmR6NkZRCkVHUE5INTJNQVNJbzc5UUExMWgz
            akZIWmlNZkxEV0I2eVoxVTFTamliWW8KLS0tIHVtWWEvaUQxUlZ0WnRBb1NjbGlr
            dGI2andnd1lNMkJOL2R3T2VvWGlzaE0Koe+2UeHWuDMsr14024rQP2OWfH+IaR70
            XKukywKozc7X/NZrC9GtiZgoMH3qBACZNFFr6P9tC+jRWKW9fixO2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T12:02:30Z"
    mac: ENC[AES256_GCM,data:F/2nzlXiSB2WAcGMf61cVu/sA5C9ToQDh6aksCrrzorhPrl5cym83EdCv30nMZSRrkH5KByr9q2BrfDAcDTt4jVixFwbs8v2LAzXFRotGmhPktzIFEh4JiaD0h0xHClvYJrWaaor/EeOujADXbCmpDsfZgza/XL4AGvI/z8c9rY=,iv:sdrB3nf/YeEne9yxugO6fMuTJ34myzWHWqN3xVGbVfQ=,tag:/PMiX/bnKXOOpsLywwpqNQ==,type:str]
    version: 3.13.1
