apiVersion: v1
kind: Secret
metadata:
    name: authentik-blueprint-users
    namespace: auth
type: Opaque
stringData:
    users.yaml: ENC[AES256_GCM,data:ExDxq8alR64zn5R4GwFGoH9WTEe+KHma/X5EB3Ow5M9xuMkwJ6ipFkBkRk7BeRlClHb/HZXjCgzzT1P2tjPfIEaL+uWpdvVJF6A1ARtxMhecI9v1NKi9Lx8DQ/qylIusDJ8/1jVJThlaaJfyIK5GxTuhQQj4mXmaZLwQRfHDMNuxrl2T1Ee8SDEav7E8x189TC4raHZadeO3zpIj/MXkh28PhP24cTQKvP9E/YBFvH9NAsElnXEObsgnx+bisRMiWmNUTSzMRkkkbdiD+CCazpSo/dC3fi0oNIW1WNs/mLMVsqHXZgB/Qt1x04+VkvqL0AGLxNuG9BCeCn1L+DrzayLoyP0wcJneXEOjTvJW0OfMd1il2ofFft21u16ChsEzEJAv7Trrdnc4OMJwVsXmzpOLTWk+q31F3DoKq1o7daRvtzlEfy1bAd7sVMKKVnSJhyWJ8UZPCtQ9YgIVdlux2TshVCPpGEafC1qSu2ulXYDTZ27+CiF/F3lICRR3X6h6OfF5QU/pkW4YVjLFsYXXzhwo9HZg4HzhUcJkAPUdK0Aket8PJvKMKmeKFgZCJnCiNISi+vjdr5lixUSUmS4gF5+z/9WGCpIo27vIaBzHkG9WKuzCPi3eNbWMPbLsVgxTcM1Vq3/Fwp/Hlpg43pvBieNXIYeqeGrfIT0fy1lPWxwSIB57nL0jaoh0QRY/Unzr+GjPL7vEd2bmo237E2wCarL9IuIeTb/rmS7W2/ibulhXs6LxknLUiIlwJBdBHXnw463sZW0p6/diPdJ52Bdy2DiFBHBfZWZFUTjtfhCNYx9TMd3/9SXbF9b1GNV07mpRyRAdNrhd9zHjPlES6hGO6d55Nc/fH8V470EhJc66G97LIqxB7BZY3lRWSqMvPTkzIcYOkVlqJEYhczVET8p8WCdKqMIq/oAG1Sx317/ytoGMhcGcVy/pcjBhJWS/MhTe3PT6ueYURwfXAnrbX32tFFQQjIsXEtd8S35dnhWHEDoLwS8xDgqMLOy8K/81CL2SPLfWgVe+C7FbTmf3mNYnDPB5aQUMEWWY5ycYAHREpBqoLlFLZ2d9D2nEbRriOiKGx8fNw6NSxp797yw1GzkXTYeYvjmDTmYpoB9EJWA1O6cqDXhkmgtc/l69mttrtHAwClhDwOdC3+7YYVG064m5t5Kcwm4BMlnpS4oaSgEU9sDPPf2UKDzrv1r9geUQ2XDMRNrXaDHjM6sOyaTBcdPUvasYGwrhJrh4cv9AcFW7sEomIyY6OgKi9ZbYJvJ0MEaYA+GVpXe4OyCnZqHrhCOdoqmv,iv:OQ34Py3hZc1ifXos4AHl1JOFLHPbp938eXnTSuu/w+Q=,tag:MnEVH2iOWP6oqV9dRamqYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMkt6Yng0UVlGZzhnakp3
            cHJmSU9rTGZYSkNQcWcwaUZlMk9tU2tYWVdFCm1xdld5cW1BUmNzM1JHZVFmN3I2
            YldYcnVFUHB2aHVVejVXcmNxM0V2amsKLS0tIExnenNUSDVmZnJteTZjVFpac25p
            dUtRazhGU0JEbndKOEdYdXV4aDdUazQKBSyCkBdrkDtknaeusOgBgyWPuyGPQQRh
            wez6xxZ4ROMc4VYPvDXr5W/LKUmS5F3KfoHfl+kareSGIuO5bb4aRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T17:28:58Z"
    mac: ENC[AES256_GCM,data:82Pot1c3UV+hNQQdUAN6FK8V9xX2lG7jeIW2r2oRJQxB827Yatl4UVOKP9Lygi/cUWRed2d2Dsmbo7lkwp2+UuINPTdZH0YcjGDXs+i+BBT09ImTPMcA5fqkiV8JYbnD0QxT8weSjcBIn4rukThuKcJNkskUk1pd3EzyL0WXinA=,iv:5dfaql3H/d+O/iNBFAaR7Q8KbNvDWjSPfRa33/8+qiU=,tag:jcZsApU/wffdQpZDnt6FDg==,type:str]
    version: 3.13.1
