apiVersion: v1
kind: Secret
metadata:
    name: authentik-admin-password
    namespace: auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SWIc40J5Sg==,iv:OyfWgtvRMgClEHtPQetXXaqvXojuGIrT5IbzcNAdX7A=,tag:NB5yWbOEAItmZ3+F6eCzYg==,type:str]
    email: ENC[AES256_GCM,data:o9a20pIHVSM/UnhsMIREpPE=,iv:UAa6iBUytswu9Skunl0TpW/V1ZTiR8VmTTtuhkS8PvQ=,tag:SIdedhOuIqvf8CIKH1Me6g==,type:str]
    password: ENC[AES256_GCM,data:dOC2LPKzQ6D+ayUS5DW69wZMkkU2hTbo,iv:26cjp2BGTnuJXkUOhsKSe+hZELdGYihmEIEnhzy1e0c=,tag:ntuTSYFhBtkkQWxqFW7rmA==,type:str]
    password_hash: ENC[AES256_GCM,data:b1P7fs1oJDbrBaxbEGHmXBjQA+qLhviF1VDGmuH7mDgRytVaMGdcWwJ3S6DpMcoF/H2/30gY5i9jCRRZuz7ew4Wj/ECif9fIncQUr48tfSSFB26DTViCaLI=,iv:v6JVwarXX/b5eW6PUOriJmDVM8c5MVs85P70SMdwzoI=,tag:4k0Bb/YFLkT7imewgB94hQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVnU0eURSaUE4N3c0VThV
            eldhTnpEeS94K0lENVdCUm9HUCtpQnhHcno4CmNLdCsvQUo5bkltOWxPemw2Nklw
            MzI4Y2l0SHhIanRWUmZhQ1Ivc2FwekEKLS0tIDFMbzBTWExwdFY2RTRrd0k2UENZ
            UkhZT2tzUHdvbmpUdXFDYlRJTGNJazgK0x2KxxoKv6dVKrW5nyu+P7PVTcZJeD2Y
            1e/nLFQ4Fk2mdflR0bvBYgqUQNZ+BicX0ZQe4m7JBM4DJumn6/1Vzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T12:56:17Z"
    mac: ENC[AES256_GCM,data:UxQQsN3COjIrlwr3UdRhzFE5Eav7AGT0FUGITWJINh9if1o1wD64wOZ2azyaVrt/+admdZENMm8Z78fSOgz2s1S4U5e3xcs2XfIwTiQ1MBhTo8Xp/I8m0cnx//kOUmufNtMVpaK20dBsbuK73jbcU6Et1+KKc5Eao1FX4D80+Ko=,iv:JVaDl8giKj7DSvNcLeg6lRlj41F+m2L3N+hmKLVjj4M=,tag:jJD5OvK62RCfmIE3vAMpQg==,type:str]
    version: 3.13.1
