apiVersion: v1
kind: Secret
metadata:
    name: auth-tunnel-token
    namespace: auth
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:38OLKv30DoV+G5sXoIe1bqt1ed4GvH8EK5E98g0BFPn2yW+hkAZdQFrXPKs31Lb4+aB/hSVTV8M7LDAbGOxa1bfLmAm0VZZE18nJhU6quWjn68em+9pojggyca8/W5er71w911kN8pSZLpw9RsAApuqcAihkZJRcDo63mR5zNG1WNUSBMZpaA232BdvCC0Kf6BeD88hCKVdZpFT3fFMQIjw76h14Rg4m4O/fFAPmem52wtZXPJB27A==,iv:7WROBOIDwJ1ykcwdMQigy41i77PBI/ajrKs3HX6YdQs=,tag:8RdYtphi/mfGMD4QGbG9RQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K0QrWEg2bXgwY1ExajJh
            L3RpWExpZGN1U053TzFGS3J0Z1dJd2FEc0ZVCjhLaTJxdWJPUVNOMkljYkxCajNa
            WmJWVnlNQWQ4SFN3aE93bkhvSmFONk0KLS0tIDBTM2FRcjIxaHlCQTRobFZjM3lX
            Y0RWQ25QWFdoK2xlMTNIS21XNkxydUEKYUbXRFr/x/Nz0pTgzDTx1zG/2mtmqkSk
            MIrEixqtdWiuTxax0HIayoiZSaAzPwS3sGViIzZHzoTtGNq4psUBFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T10:59:13Z"
    mac: ENC[AES256_GCM,data:wc4TewFcrvfbgbfFTHA9gs2NYMh+y0Z0OTwbqX9nafg+olPfxCcvI2Gijqbe7MTTf5LqVZfzOHExO2oLTyiSd9IsStUPMBPJ3s6Pol4Gr8cgMnC/A6nc242AxJdtBn/Yk7ayiuVT/bmW7NHlDJTZyD+7Ff2l4MGovmHIOff/UXY=,iv:/DMvLgcobdfyRKep+KUpEavy/yZTUQT0td1pHdSRQsU=,tag:oV743hakZ4mluaLmGRgojA==,type:str]
    version: 3.13.1
