apiVersion: v1
kind: Secret
metadata:
    name: authentik-redis-credentials
    namespace: auth
type: Opaque
stringData:
    username: ""
    password: ENC[AES256_GCM,data:nItPvfV4tBbRlwLh+yR3sE0b2Jl3my3vbhFUlqnkkcOwPnLX3JLWJQGfLQ==,iv:znehWsyAMePzuDvTKd14KF9QzakmK5sxoCqH5w+eWk0=,tag:BQ58NFVPalYGGJ2wgKYb0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdmRvZjZtVzl3RFZsMmN6
            dVhNcFN0NDczdityK04xdVdxYWVDblRyUUcwCm41RGJSUjJLOWlBVU5GcWFEUWI0
            ekwvbFNLdjBmR1hsSHdpNWV3UFA5cncKLS0tIGdxb1g1alNpOEROK1VOR3c1SFQ2
            R0s2STNpcmhwVVpLYXNVMDMyMFZhUjAKRnuR5HTxauqhTVYor2OjBiD6RSYeX9aX
            227dJrLKwaxkPgf+5CAL4DH7YKFPoDGabnaXD8l4wPw289e+aOglyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T09:48:50Z"
    mac: ENC[AES256_GCM,data:1fw3BB438KucGXAMCXsLxORcbA+fdVIcerxME7dgudIOU1Nplxn5AtnodotFlQw0Wk2sqNtAfsfe5h9LM99Sg77fcen9+MWTsioVesBGlu5PqgKXmWrHYCxBApc/3SF3p+27zFhY7JXs2KHLKGdyL1q8BnYT/eoFVMsGU1Z61BI=,iv:u5AtpAMxSsqRWz3T2mRfyduYnIKu9EaLoGm2CzR7+Ng=,tag:68H+UVzsiJOsiE147pBYBw==,type:str]
    version: 3.13.1
