apiVersion: v1
kind: Secret
metadata:
    name: sylwia-authentik-password
    namespace: auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:oSuD99pH,iv:ajd/t7nZu2yZ1AAyXd1tyAqlDDhbgGhwxINwg7cDyJg=,tag:ij0F8KSgpMyw5YjOl9c8dA==,type:str]
    email: ENC[AES256_GCM,data:ZO5OYlVwOZtPFk2OOM2MS7shAtw8Iw==,iv:eUYOOMljvsbpgi4h8HasAcTyku9puw/Xpxd/n5ns/FE=,tag:g+8+U+cbgLojbhbmzQENlQ==,type:str]
    password: ENC[AES256_GCM,data:2tXW0QvXVpIxVpg8zgNnqh6ZbfH+2SvrGOnS,iv:kBLHoIgaDOBKb0MfKRF+GMswfB4ULZXv6tPh2mNcJMk=,tag:4SL3xxyeAYNuTNFvr+2Fuw==,type:str]
    password_hash: ENC[AES256_GCM,data:EEvyAPBjMFWo5613u6sLfjqLj9pSavzoHxZT,iv:5DihrhoKPqaXbvnXRpippO7nf5NXwW3pF36zMbkY8Uk=,tag:gSuZJxGDy2Lf3c7hLCimgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdDExRDQxMVdhZ3lkK2hp
            U3VyTG0vd2tHdnBubGpyYzMrOTJUMzduTkNzCk1zVnJpTjRoanFTUmhYVWUvT0pG
            dnVUbHNGUk1iMU1sUGphMlgxeWQ1R0kKLS0tIEUzTG5TQzl1U1BRc2UxTUtwbG5G
            aVE2L09DOXo0bVZSMkFjYlNyR1RsVjQKUfdQzMQNv00C/hV3a7k660ttk74H0wgO
            3YdWRzFmdTN9OiLOR5UNXrOgzrN4ybi2WNyrPDrKflLXOIb5qOefew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T11:16:29Z"
    mac: ENC[AES256_GCM,data:M88tL2aVWBsp+weFNya09s2o/C3LdthcVQM9hvEVtJcho5NCSiY1UKzntjGLGptUalBzE9GRrR05ARUYDMBvgJnx6d/YfXfs5d8q+a+pp/btb4YLZIIQwMUkYpeZKXg5EzastvuK9MQL60vdq788h9I6MJEPh5cVLZACoX+ka8w=,iv:4TLlJ9IAC1kRSIl9CzWve/1dusxr6G+1Tq4ABh1HblM=,tag:21m2PM2k1rS+auo8kgcqmg==,type:str]
    version: 3.13.1
