apiVersion: v1
kind: Secret
metadata:
    name: sylwia-authentik-password
    namespace: auth
    labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/part-of: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DJEh/8Kt,iv:hLRj3VGofVyaJFC9cBFN1C4mX/2jGIxYeMFMtpuvTwQ=,tag:KdqS7ZCeAGXyG+oSTAcV0g==,type:str]
    password: ENC[AES256_GCM,data:eU+qCHow75KUcPhWs7OoaRD7DctseqDV,iv:bb47qthBtybp4ZL7kktGZIr3K6Ffg+dBgReYSNc+ILs=,tag:jR7YBOlq8/dhJYz+VRy3mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0tJZkl4WWQySDhtdTBl
            d2dRWWZCc3dSTWJVeG1wZlVQUnJXdDNQdmpRCkM3TTFvZkdScHArU0xIV0pVSGZO
            OUtFcWphdDFqQ1VZQkZ5NFBhTGZsUkUKLS0tIEFVczdBSjI5UU5nT29CdDA3endG
            WUp3RnkydnRFN0JrMW04MVNtQ2tpNFkKTsyYHEcCTt4NUg19PlFcZKHeRAdEIWyx
            5b1C1uUQ2M/grvKHIX03KMrJOOSS4l4cXHRvKwtstTl3b44RHQ+H5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:00:37Z"
    mac: ENC[AES256_GCM,data:EECbkvk6BjD5oPJu7Coa/Ewx/O5TTJdgejXui7sesfBgYw4gO+WQNTkJ5LCmHOdPAajobDQL5DO+RTBkxhV8nw1opRsRK5NG0TPOpQlvd2O7HGCQaLgz0Av05NMqy3ZNsBtL/OFmF3GVJfwUm3tRq1q1vyd+NEvNJVH/XHfmfVI=,iv:FQMa/A0CDKbOSGeBhh1oNRlUVc3JFMy1IusqXl6V5aM=,tag:V2SMLVocb/rGbL/rlmlZTw==,type:str]
    version: 3.13.1
