apiVersion: v1
kind: Secret
metadata:
    name: sylwia-authentik-password
    namespace: auth
    labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/part-of: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SiTTYm00,iv:iBJHqwGJO8wGai361zriSdpd7an976dne8pu93sNIcs=,tag:K+jpzLoZ8qoxpnjr6hEp5g==,type:str]
    password: ENC[AES256_GCM,data:LpLN/e+eSEHKP/Ifmv141UcKLHfGCHh1,iv:FWsMxNA55OBZiR3CApfgtB1u1PYuwNlvB/a9o0E8mEI=,tag:sGTcLO9gnsWEJQIvB82KbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdHdSRVJRczZIOUZNZW8v
            bG93ODFRZzUvZi9CN3pLWW1UWGpiNEdRd3l3Ck40cU91aUcyUEtrZk9ESkxJQ2Rq
            c3NZZWt0WUxZNXlVNXZLT1gxS0xDa00KLS0tIDAwQjlycmtmeDNyRjBYZWFyOFM4
            Z21LSm8zcGxPZld6NGdPZkI3RTZDM1kKGsBcdpp4C/oOw5E2HD2sy68H2agdUDRS
            2rEWDm3kSjev5nLMO5/CgbLK5Sr8yJiO/CMqA8vOG12RFFJECJtKdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:29:37Z"
    mac: ENC[AES256_GCM,data:vqUyEotlBTpVPsqDjo9lZfjL64ZYQWSmYu7mjZ6uemsuD5vuSG+xwiCZO5t2yeJ9214h3Snxf+jfMNmAURZyeojuuNiPDzG/BSlgfX0Gc2BgW82Ebh6olg7MxOsLztQY95wZ/rAdVxerlj3dGqlH9H58AANFLxRsf/DMu2iQJZg=,iv:7AxkhTIxA3tgF5Ax2eoKM9OvPPy7kIIG9iDg44BWDHs=,tag:/VKAe+nRBhg3KY/0SNQu2Q==,type:str]
    version: 3.13.1
