apiVersion: v1
kind: Secret
metadata:
    name: tldraw-tunnel-token
    namespace: auth
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4LwKxi/NG9vm7pnB595/He5lFaX9HYbQc1Mug88cEYKrgDtMySe3Nt5h4375uClvcMWU3thQmieBpXVrB7W+aNnYqG4l61c40a42rGPJFd2NJbYd5Ub+bCWb5OvuIfo3uwHhQaKZGWH2Ie8x2Y13agzSrUKdJd4JnTTPJgAyYiJGMwlI3L39LDoSND+tw4GeCgaxljazBdArcZ8Kh9O3IoepxzN2ycoCqzfPCZZrCFOa+KMPr/Wjkw==,iv:2L5XPtEDpDqWlyAg+nCtDR/8RZNlzFHhUKNv9Vni5iA=,tag:sQR9ATRxlEw29t1YgkbsXw==,type:str]
    note: ENC[AES256_GCM,data:jhYGwhxX/WiljKY0OAWJGryJLnooRTLXcAJpUk4Lei6QT+F66hdcvfmMNZlmsvyZPl0M,iv:nT5fbujVKdsWWPT1rpc4b94uJG71y+doBvW8uUejeTI=,tag:5EykYfkayx34/oyKtgl48w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbGw4UEgwZEtlL0pZTTYx
            a3phTFdCUFB2S0FqbEExZUc2Qkt6aFdsU21VCldSU0FLNFVJa2dGRFZ0QWVqZXdw
            NHJEU2dpK3JWa20wQTR5WXQ2emZiL3MKLS0tIHczRldvcSsxd1YxSDNMTDNnRXA4
            WGkwREFTZ0h2dTdJeWlvSUNaUTBNREkKJ19MLITX96bhUJzXSpgebp+kL0s+Fzk5
            8+DJvdHMWmAHclalu+gh8IFaBPwrlV1uUEhI3NQpxZB4ZPzoV/HkaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T12:24:38Z"
    mac: ENC[AES256_GCM,data:czQ6zAC8085OqwpogCSnLyd46ukGz4cM5/q7qqcCDLVwzaiEjCCdYadZV+K3LH3BXsgLrQ+CkHBC9Eq18f7L17bUkKrSpqmRQUXZ3LAe1CVWiS72S6SjnFiYSSg5PZh9wTPhObFTqBZX4dojhzJNXTj/3PQhwEgsvF4eUAEbcuM=,iv:phj52BKRdasbFQxC0KAcsyA7D+zPrZhUDNaGFGZf9ZU=,tag:4C+EtIXpgjT0UjttdvmEcQ==,type:str]
    version: 3.13.1
