apiVersion: v1
kind: Secret
metadata:
    name: opengist-config
    namespace: opengist
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:RZgX7Fm5a8nJLWLMhjSPu3FDdeXH1nue4DfzLHG3bHTAGHVlXmnhOnA5knEZMsTUk2ubJzeb2Urpzpok3b1k9XU8neA2zNDvOyf8BGcJL8frTafOMffuPat3S8QwhJFiJdy0INJOJjUXNXsgH8RwHcqx7tb3nM5XUzau0gBHxrg8++WKaYeZultmURE0Ul5FmIZ+UH7f6FdDSw9vsVEkKOeJAPYWA1N1VGEKuPYERi+y8DB/hEfrFgqkVpQlPg+kTvtqk8yNKQSHugEVUyc0lFsfMgOsMZJhzN+m5fG+/0AEODmb3xLy6qf8NC3Uzm8l4V2jGfnuMBJcFpmIjMtt9ol20fAQjbcJUDi+1QLJzVqRq947eINSinGe88qXz24zhbrDe2VpsmqN1fulyg2JhHCwYAyDlwnOfMTkx3sOk4fwdpZ/oeBSLoETTksvod9DbrPYQCrDbPzXnCvO/gaN3ZWQLp+bwTuMFqKpaEDbfbcD8NwyWCX6a7z6FS+sBjXvEZjMCD3usbh71ZComLv33yE+Ooax54WiFnVLwZqzF654ZagHqNy+bfB7iR62uB5VbNUTpUkZycpvJ/4a25HewExsSwwiFhF5FobXoHyZloiX9gvQMKqB8UwG/rKiF1V3bsl6e87cQ+ZlkhOIzgIlnuTjFjo=,iv:2S3AnqW35O8MBNpi4sDYLo2tnZkQEn2tfk3IPPbEFOU=,tag:nhHBjfYLWFDjZSTVJmjpaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeDhTSUZGNHVSZ2FIdHlZ
            Zk90WXdDMkRibitBTG5SRjVQVzVHUTBJSWtBCkRUTVMvOGozNkNrL0tTQ2lBczdq
            anhXV1ZjZDFmYU5BaFBReTZiTTFxSDgKLS0tIDNyd2NicC9IbjdtZUdSVDVqenhQ
            UjhES0JreWQ0Wm9Kb0lMZ0x1Yk1qQW8K+S3pw5ZbsEMeMZVCcvENFB8jEWyA2ffl
            690hCa4GB7tGVp0hmDN6+620s6TxUc35cye3PLDwp/xhHSkWtuZdFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T20:51:11Z"
    mac: ENC[AES256_GCM,data:Ub46AmA4B5Rf+4DEOAOWHiZIVvG5xSEWwwCD/cTMM4lTHEU9iwRb/NzR8DaxYOcvUk0k4ZXpQfFROuQlCwrs1ZU1HllvarQFyn3lLUc9gaDRK58BGNXxhcnr/zxwUrjY3euliuzYiR/1Ferhk1r/qCUMz0lePBN9JBekpFkx96I=,iv:mruBLUbFZ4s9VKsHsNFaRn/3A/RAE6XYHbI3GpPP/LQ=,tag:4QzyKHqXykrQwHy2IHiE3w==,type:str]
    version: 3.13.1
