apiVersion: v1
kind: Secret
metadata:
    name: opengist-oidc-client
    namespace: opengist
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:kC6ltFQiDQUkGxTpIwI7z71MBuSxLZyPLU3bisQjU7Y=,iv:chAxY2pT4+YMzzSsX5mbXHeqRfbkYemm4Bl5QlfxjRs=,tag:mf4+MXPSDrI5hCCvU7mJxQ==,type:str]
    client-secret: ENC[AES256_GCM,data:+iKs3gCVwxlPJSvD+y/034DLJJmy08+I/46Gkazb4ZZR3txTEyh7r/s/sA==,iv:G/7v/DQxfkOKtCeCIb++jBlHb/d4tmrPhwZweCgxrLw=,tag:C/G67c7kj32NiiS7YYvsmA==,type:str]
    discovery-url: ENC[AES256_GCM,data:Ad9QheBoyJ30B2qmjH9ZrjpUpgTBZm7i+V/XdZPyjKZcxUv9tYkzP/A5ZvaLvmdz1GZRsGpZjlToRG5acjAB50WIG7/HI7201/p0bfpKf+4=,iv:f5MKAe0MbvWWjzGCX193+8G4dS/MejUY+6EjrsaEcIw=,tag:BE7PzCV+VfIo0CSI9R6BMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT2NOMDRxejB1WUFkbGhx
            ZUdSZ0ErVFU4Sm0zWWtHMndUQzhMWDRnRFcwCndaNU10NjAxQms1VWpwejNkaGFQ
            YjhzZTlBNDEyZ2RZcFVKeWRtbTg4WGMKLS0tIGg4cGZnMU55bWZTcitMUU5KU3F0
            UlB3RlJ5ZVNISHB0UER3NWwzRGtkanMKTYBI2J4nL8O3r0p1JxZnQseBb2khh27Z
            hPa+N2EnI4cyaNq/dHiynmpggKrG6hEdolucxldfvjAwPGJsuY5W+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:47:31Z"
    mac: ENC[AES256_GCM,data:wRFoG5TWe85QbZrNPQOsVYp6kHaOSXvGMOt5aqnBGqVKZyGekvhYIyBNriZ1Q0s8Rjrb1BdmVZGFiQp1bIWFCHUjxGT3UhO4ODFfcdFSYLJ+DpyB81XLVg4Nh178h/7FmU801VENptZYJFCxqFgEHSo07QiGQIq2oF97WpFbK4c=,iv:DiMQPHPvK3wobdyQ72gqJ5RfVyvd9Y+jkEbBlnUsbvE=,tag:u2VcQiABk0335vMafKU72w==,type:str]
    version: 3.13.1
