apiVersion: v1
kind: Secret
metadata:
    name: opengist-mattermost-webhook-url
    namespace: opengist
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:qkuguQc4BdHbcM9OCSLGNnv0cR386Jl5zAjGbcM5MOQBPo1N2OdmGT896MmO980=,iv:5EDIqCvvGjF3MNaUw/D+/rgL4nnq23+TyybXR6sCn5o=,tag:9gMPoQDMMpb2l31iiA+29A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdmZBMUJGSTFlUGxxdkEw
            YmFSQjlDc0orWjBwRHcvV1ZHNlhWZmFSVGdrCi9kbkYxS0luRU1yL1VwdVRtRDlR
            dGx5clVTOERQK1B1U3I5RCsxSzZFc1EKLS0tIFpBL1EyVU9LdStpSlY3dkhQTFRw
            MU1IQ25kejNsMWwzWmswSmx5YjNaUjAK/Nz3UZHwQeY78QShQ91wdrckYN9zz+VP
            hYif6LouoO/dU+fcY2/fS1qKUWb6t2UwGnmAnHymxmnbaRBXlDKlSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:47:31Z"
    mac: ENC[AES256_GCM,data:+j5qOet9L3ID8E2Khka1HuIKkGWNQUYEYvS5cSBvAFqW3W5JD+5H+xBmUibmb+fUkIo+O9uiLGUHAHU0fzsmprqli3HVVZV340/xYDnWRgKqRHBOBGG6t6jjYCrSs3BZ9E6e7Qk8OclQoyPxxmE4xnM+jHWo9V2KoG3W8+AwT6c=,iv:zkw1zfOkRHNdnhGvVkvXXIscBH5+DAZ/NQwYxT220hY=,tag:fH9PyLCZx/I+TDh5QYN0tA==,type:str]
    version: 3.13.1
