apiVersion: v1
kind: Secret
metadata:
    name: opengist-db-credentials
    namespace: opengist
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XIQqXC52YoY=,iv:dnKHRV6Fb1zRiqF782qW1cE1NbX7v3QS1Si4dSsMD20=,tag:AQLHxhSZVHRyYO/9/lTlHQ==,type:str]
    password: ENC[AES256_GCM,data:BrsBFqBrjYWYSzss7n82bn+wF6U6UdR2UGSDT8qTh9d82d1FClNGut7jpA==,iv:DsKP60ZF65mAPTALyuFYbGo7jN51TRgIOvDG9/YFlFo=,tag:MZFr5duLqr6G2SQHSzpmug==,type:str]
    host: ENC[AES256_GCM,data:egais+WvOhkgxdZtrSJgYM4/aDZnlXHv6E4Wq1fp6tY0n6gg8Cjg8+Q=,iv:LI14zqWNDFbg4QBEN7oWjCIaadNARupXo7paGt1KvEw=,tag:dS1+TvMS6wO/Wjy9DS/GmQ==,type:str]
    port: ENC[AES256_GCM,data:8ZsvjA==,iv:TMRKbKto8CoH1kY9/Y121dLowhWR6SRJfdsBHqCmIt0=,tag:o8AqdhOcEUU21q63Q+AJgQ==,type:str]
    database: ENC[AES256_GCM,data:HgkGG3mZCo4=,iv:N/a76U4bU0QoSigS+k2J62TUhg4Q4tba1cthgW1U2a4=,tag:+26BYXR6doI2Ha8u8l4xww==,type:str]
    externalConnectionString: ENC[AES256_GCM,data:u6ATqLiD1Q/J+6PnBUBQeTb8wZW5Fgbyh+UcFIoRQivi+cmxR1/dRMCU+NF+ZELJ4ezFWKHzgGA51uoNt2ltU2QonPMOxnhO6vZDpihvkEInW6w1stTTjMbuneVpjejHBlCZEiYMs70Ftrw8dMjQ5WHOGkz3DOU=,iv:OqeTJIufw6d/0KEr2kNmbd1QtO6QH/kG1A/VvWLcx8o=,tag:Jr7MQKgrDhnJSsFCryJljg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTEpSMHd5VGRxenJlZDJJ
            cE9QUHB2R1oyK2VlazNmanBNTVpqd1FrSzJBCks2VjNjRUE3N1hSK1RjSDF2bDVU
            eXZyNjI3TEp1cjJ1SFJ1NVR6VDlObUkKLS0tIFBHRHc4ZDJ2dU85c2MySHJubkFS
            Q0Q5b1J0RldlMWZTR3AzS3dqNDAxUkkKVulc+B5akfL/DZ7R8Sv2HlHSTH/w22FU
            /Rw+qei4E/rSntwFJWjsev5QjUCFDIWEM0ylPP966MBmwK5CnHwSXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:47:31Z"
    mac: ENC[AES256_GCM,data:bU2piv39jRLl3qCc1488vkjEx4rhRvoutOLFEIk6Xg5hKX8Zzc7YJm7wg93NK2A+k+dlJhhOtHkCpw0WhuyNeCiQdbWuZ8R6r6ohGcZB7Frqa6YDMBG7skUOwGZGl5Zxo5/nA9EyUxZ58V1nTxWrN2JeEbCBs8zhIxQfTqo5AOI=,iv:WN1n0NqrNPHHXWh+zrfkVtmeLAM2GLk013hz7jEsDC0=,tag:W1Y0Fj+u70EiTkNUJugkgg==,type:str]
    version: 3.13.1
