apiVersion: v1
kind: Secret
metadata:
    name: opengist-config
    namespace: opengist
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:SBkEW8xADoqbi+7cAFqWtIal5f4bDQ17o6el+GcCM88vpSvbtt9fEmm/lc2PQ39+2U75vN2JDmnfuXrGpOxLluXOBVxv+yfjfybuFtaTpWro90isvOKMbP87P14cDV8vcSbZFbClrrpyyTgpkvD5EcjWlb6FZIMnja69FwJ7kQFQMgPiyoZTbZoGRhF/U+e6HKT3idDdzeuaO5nG3V3AkiCDgna/DUokMWViMIxOl7oPJ7el8lRl9ojOksF1J+clR7afs8kaABG5lUd7PJyZ3mPXULRNSaUH+FWe+zSsyH0Mt1JwYElf0taABRV2Aeuc/u3iB5tAft30WatQ+NdNmrnYzIqpznfDO6oKvQBiAXj+fm/luOTTpO/Y6AKTpxhEYlwTNq7dfJHHDRlKv8amsA/2jJHqfKf+KfrZ5bKRhY04R+QZ57wlsRu5HVHPnKoIhFzUyGtvbSrv3l5RRiwSzxO/TZD9wHdYJ+AIzha6aocYQ36d5Rkt0iGNLUblNLOXO1Zdmi8Fvay9WaCPIsJF+3oSl4dx2zH3e/ogBRGWzK637iknCXy9rAnztKH4S0MKJn05iFzAfYis6C6vzpNg5AJCcmIW6/UVygkcCu89QlD0V2IZv3OROkIfHWrZtYHVIfIDiQ+/GWJ5pDV89UqWMj6yk54=,iv:oC1xmRMRBBihMqO775KM3dmgxp6kkFdmNzhfoOFulNs=,tag:DyYCKXQ0HTYdx4hoG8f3sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUVpGSC9PVjhjUDAxV3dR
            UjNVWjhFNHNTT2JjUWlwSDd5RlpGdGhYZDNNCjJUWWYya2RXOHc3Tk1ETStaRmtj
            cnozNitURlFyd2VXK3g3VlZCT1M2d2MKLS0tIEQ3eDdZSVQxNWdCZmREVVJNdGRu
            d0ZURHBjVVdJTzdpdlBSLzBDbHRXQWMKTzGiuyF3KqNL2oiwfkdODJt0ZEtRbQL4
            IaiCkIZmN7triy6i2NPG8FVIWbNtoI6hBAcbBxXUtFcFPAbnL3DFSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:47:31Z"
    mac: ENC[AES256_GCM,data:VRgg8GY8TQt2AgiQU3Te99rwyT/mzAXrkBYCcOzgFAos9ZHwduk/ct91pt4HJUkFqe2Hv+BYWQiWQeHJNeCWAYG6Oe/HomRY28PKmJiRU7EmGUM8iyMtsNjuhUOKs/Oufb/ySESj2QjDSEmxl60cN4QLujYeO+mh6uXqCbJd8EA=,iv:7pzcsLFjT66PFUdfIgZ83TepaRWJgNOhw2IzTLWfpKw=,tag:Yk60mtnjIqAx5YlZE4PTBw==,type:str]
    version: 3.13.1
