apiVersion: ENC[AES256_GCM,data:moc=,iv:TEYi7s9LITBDkDyBZtxNkwzVhSM8q+NdUIhrfIfORYA=,tag:T2lAVHXv8yXyAy9/vffj0g==,type:str]
kind: ENC[AES256_GCM,data:rF12f8BH,iv:/JT4K5b0EojoNkT/iBwWe2hdtVRYMH1FAIHSgV8DA6o=,tag:nQy3Eb2yMR7blD2Xcg5rog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0hYLzfgghfkuLi1a+YADI766ZINhcvA+fc9f,iv:rvfzrJmkpldaZd9lKWs0RzGOwgPtyexD+Xk4fuMeS30=,tag:ikAVed/hNmGYVpkpSPsfOA==,type:str]
    namespace: ENC[AES256_GCM,data:Iqx2zYrPUfCxvgcipg==,iv:fDd7uk3nWwZfQoqBJSW2edt4ZtGLoA/OBQ+hnMNheH0=,tag:IGKplS979HdbOrcoOtbQIA==,type:str]
type: ENC[AES256_GCM,data:n1Q3SJtx,iv:NwHU6sViGySYw8BRG0aquZj5N8hsRz1M9pvhyrlG9zo=,tag:yilNCbgDCkucYiTBLkDtKA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:WnILmBAw+0zUKPtq,iv:KA7ungk+GxCz6TatiT6PHIOWpDwDF+SoLS22+/nWNNI=,tag:Uk5HBqCTk6JmC8lx3M2Mcw==,type:str]
    password: ENC[AES256_GCM,data:Q6fdvvS25Kx6kdcsNjw3ed58/RiAIip6/aB8MZnLSfkkhXmg3f6wXA==,iv:pl+ezBwxgY0ciXauU7Y9cKGcbSBTw94wg5wHw0MxaGg=,tag:lkWK5rbxhmAbT3zhfjzH6g==,type:str]
    database: ENC[AES256_GCM,data:NUqcKzwGh89H1dir,iv:H9y8GEZTW22+jPbi9qnZsGBxlYPlRCkvq8UFkmwUnp0=,tag:QndRb/Gy7BPig8NbDaUPZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbHhJMzQwSi91NnN6a0xO
            VEV6MHQ3RWxEUG03N2NGU3FUQy9LZXF3OVZvCjhHVXRIUG9XRzlFSDREQXNsL3JC
            OFlLVG50K0RzWS94cUFIa0lVb0diMkkKLS0tIEs2NEhlRmcrSXhmS1dlemlWU0Fv
            S01UWGVtUDA5QlpWMDZyemdJSS9RS00Ke6+eVDK54ZQOasDVVmTFIHUPNwvuvkOB
            iHVcT/tgHCJNV7M5kB26577Ve1W3QRli2mOxu87DQBWCnaOAXNC4rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    lastmodified: "2026-10-07T13:55:40Z"
    mac: ENC[AES256_GCM,data:GxUWw29qkdtApce9mL/qwRLzsNqy8ZChevTbeZnatc7XYWMtJfzHcBxeRSY5T0qYasiJ7wgxz4NFiRJkmZDZD7Jrtm4KAot3CMtPBxPpOeClp2IfUf5xfSpHBZtGlsETOKaHt01syXatX55Vh5kJfnWDyVbPt2N/HQjHN4r1Cn4=,iv:LDDEOGpi2XWKx6c4PubBXYyAv1fdH3mO2RFwNEVLEj8=,tag:xspumEr4WV6y8aCak3sAQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
