apiVersion: ENC[AES256_GCM,data:PM8=,iv:A5G+G5FwotDAmJjzejZnL2NeXHnRJoEHlFdo4EbNB1s=,tag:rOnuz85clEHdixZrng1gmA==,type:str]
kind: ENC[AES256_GCM,data:xRUZQCG1,iv:KqPThzvfvX9z3Zxyq0hQSW7kPnSUVdCntHAosJCsGK4=,tag:BSKCcwv3vxMTwf59DB22eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FTUy0D3FbeLhHUKc68uswNq0DJswxKiS,iv:2ZHZcZGDjNZSoBct/9Ip+cAEbUAZz+t5LJJNcp3ajOQ=,tag:PY3fF2YHDMpL7ljxctAMhA==,type:str]
    namespace: ENC[AES256_GCM,data:uJL+XjnWBZUD60rxpg==,iv:GW3eeX0JPRO6KWkS/Zm62sTBCX1huJ0lF0wZdgW1ZGU=,tag:aO0oRSP6H1+WxJImM2vi2w==,type:str]
type: ENC[AES256_GCM,data:PdwDjZuH,iv:1E79Mvi+68HCUUSZBuqbznuYj5+p7WFRAF8NuBHq320=,tag:s7K60FYuEUcsvGBLvXcO9w==,type:str]
stringData:
    Authentication__Username: ENC[AES256_GCM,data:jpSR5QU=,iv:yFZqJC9WGYcnWsjetyOyJrUEICzNAZRydDMRPlIpgn8=,tag:pk+MVW+bp+Oa3v5UJ42kAg==,type:str]
    Authentication__Password: ENC[AES256_GCM,data:XapMIUv9FZAJnNeW8YcLlS+c/dh5IAKGGa3s9Q/1gW/ojiDA4fdDJQ==,iv:t2YS3ZhMrC+9ryREKRXVtAZVvfb1hmXuF+WXyFsThaY=,tag:BlpH6MB3W2Twsc9o2D7OIA==,type:str]
    OAuth__ClientId: ENC[AES256_GCM,data:hSi45/M4vn1EC0KH/cSPkOD5TYAJw7nekN72IPKTISwfjUGNnOHCG9aq0p+fYmFeFzMFydZ9xvc=,iv:yK4pLU/BppGYeFAQ+cT5epnIXacGyzi15ewAt4p+B3I=,tag:9BUljv5HjSWOiz1dYT6XnA==,type:str]
    OAuth__ClientSecret: ENC[AES256_GCM,data:Cf5gnJRTrc/wwxctuBOYrcaD5c8vtcmwdwLtU+wkDZ/yeRMkl/8KJHqp/G+H09M0LtWhclrWR2YakOkR,iv:GaY7/Mh7LedRrOyXsHIrr3sD8pJWF1jmg86KanTK6DQ=,tag:k3EZM/yHma+iVvHBIDYtfw==,type:str]
    ConnectionStrings__DefaultConnection: ENC[AES256_GCM,data:JoM8W8zpNtowZshwocOxscf1KGhxCcxActPblIg1QylI/zfYm9V9/Y2/hHK8xeLWk3UW9YALcy3v3wlhF5kdRfx+MwlOrScDpAINNxhgWWxu5IDHG7UAR7Nu50oIQZbInAjlCt05MXqxqkjjlRhZQgO+n2QGMXQ1bO/RSH7zAAp/MK+223arZnQITI1G7BoYHBIoXTzU7Hix+ZAemDqf,iv:wPPxBYlUeJegOixhemiXQQh+o6dgNjmC7MVoIvAlzrI=,tag:3tJHBZ/DsbUgojNKSC4Xtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWksrdG5GSERPemVDL01U
            a1htS0x3bjgwZ0h4aXlQbTZMSEtOU1dJQlFZClhPRGJPcFlGOFM3Z2sxUmpKSmM1
            ajZBTWlleFREYWZFK3pPSVJjRUx4WHcKLS0tIEJlY3lPQ0d3QXE2TDlMZEs4Y004
            Ulp3OVZ6dExveG5pQnBiYmpLVXJxK28K4+f0cTH6RuPxSJginMplLoQ5Cam9/Twc
            I8rBoyKFQNnWPdJ7I2sUAra0oB9YnRecu7eH9T66UzgDt49w4CNYzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    lastmodified: "2026-10-07T13:55:40Z"
    mac: ENC[AES256_GCM,data:Wk7K/h4h4grYRrGTCW1EiWe+z0jlEPWRG2+HYqHPfDn2Le9Hf6qsuvWBCzNpVMSYZZyGkexuyXcPmH4OIt+V7cGoJ/gKbQ+lEmqaor0w62D7MBkQ6kCywelpEEDuYzrCaRzv5yFy9WCl3mo3cGCf3BvAWjeArhBZ1SXeS9fLw6E=,iv:2Clt51KrqN+ZMr4h0RkRyDOUYyHfmIwjRCuEwgOkzok=,tag:DglxoswjljY4CqUg88e9TA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
