---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-nodeport
  namespace: arr-stack
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
  type: NodePort
