apiVersion: v1
kind: Secret
metadata:
    name: litellm-user-keys
    namespace: llm-hub
type: Opaque
stringData:
    wojtek-key: ENC[AES256_GCM,data:3p6zfA006DRcPfgOpYeA1ofxezOmKpmmSQ==,iv:MM5/5te6ehScwfEA43epvKVsT2Vpm1CjIh/Le8aN8BQ=,tag:aCYy5l1oZxp+CIrig/FyuQ==,type:str]
    wife-key: ENC[AES256_GCM,data:9UvKwgjRs4LiZsTSBVSgaFd1titeflxpaQ==,iv:ax5hVOmX8WCFHwOA5hvdQ8Pcv/TAOF4FtdVDHmKAtCU=,tag:qXpv7rVGsIItZq1DnhmETA==,type:str]
    hermes-andrzej-key: ENC[AES256_GCM,data:+3T5JSoOUkqoItS94N3wSutctraEPPuXKw==,iv:c+13od8bPG/WsXW4NltAelxG5nvQ+lGO9gfHUrBxWzU=,tag:lPe9E+iRESKgbLTuE2CnIg==,type:str]
    memory-honcho-key: ENC[AES256_GCM,data:KbQBe/b8X1QgDLYk63yLucZKQtJUldlwtg==,iv:MXSvfmoxgnHY4WnA/rLgsxTYZn5rYYconMchRAP6PYM=,tag:4ZaF5ONwEFvWRnsVXnDV1Q==,type:str]
    hermes-bill-cipher-key: ENC[AES256_GCM,data:Be4XO5P2zYKYQ9nDbCGpa3KrJ4hX72V9IA==,iv:rtQTGbCdKsQawD9E3ZfiTLFONFuiqDLvkxi9NY6aTsU=,tag:a5u6RffmFj5u3iwdXo1LYQ==,type:str]
    openviking-key: ENC[AES256_GCM,data:uDHr/jLR9poFY3CE3Mdm0V/RW5my8KRMMA==,iv:9HcjlPkrtUoYEtapueueUHFa/k7cpF5LILTdQcBUiQw=,tag:KkJPFiicwCm5TiTX/pC7sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NEtESDNaZG5LZnRoY21V
            NlduWWxPYjI2LytsM25Ebm9OeHAzb2Z5LzFFCkV1N0U1ZDUwWkxBbERIZ3RueVZC
            N0JydzBrM2VadnVBK1RvT1ltak9VK3cKLS0tIHFqMFhpODkxL3ZPMG9qUGpDdDM5
            VmlFeWtEOXRsMEZNUkdwakdBOTNRSzgKiyL9Brm0bOWBzDaMBzlgwJs2J+4LUF8Z
            HVcsOTQ+gPr3P8J/nyvzd5bGB8E4CSRqr6p84iiWdFwuumyt3rYyAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T13:58:31Z"
    mac: ENC[AES256_GCM,data:hFQ+rVudmVH0yRvkTf3uEmTc3vn7eRQtofKEQ0zuqN6qc550EMs+tWIAHFfogFTXv1VPLvtvJeT0fmyEFufBvrwxvw3rr3yXr05ID5STr8BHZTQB0sf1MaSd1Oyald97RQb96VB8xRHTwn3d/+VlQSuhrMSzkkHBo22c5W9zakI=,iv:ME965lAlkDn93K7uvdyyS0ZrUUVKSC9g0Vceps3wBj0=,tag:dkwfLmsGKhXVzwBDlKgq8g==,type:str]
    version: 3.13.3
