apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-credentials
    namespace: llm-hub
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:YXPTQHyuMg==,iv:/HfD1G48K6OQjylcAmdSl0k2iDO1KAZhusrAEEpMf18=,tag:6rJA5+9CEyYlmpTBKLH6tw==,type:str]
    password: ENC[AES256_GCM,data:ggWMI0HockxRZsouqtlg/+j+TRmae7A9,iv:k/zeGxiBJPr/phNikND6du0xi+eX5MQ65zx0O9KTnuI=,tag:t8xifr7ia/zb7+hGg7K4Vw==,type:str]
    host: ENC[AES256_GCM,data:svcj8o8KBmFhMV73ReiluqLHI1e/7NnzBZ/O/kVYvjytrCrXa0Hx,iv:3lWMCapBYKDmevRKhPjZgVV16makpupjQvbI4zfCK5U=,tag:mPLFqN/37U76XliH2X0Fxw==,type:str]
    port: ENC[AES256_GCM,data:58bPeQ==,iv:prnZmmLCE6DxVC1FL79qcjrqSQmCmSinrilLs4noFns=,tag:GJAcMt7+PDWcXmKl28t4sA==,type:str]
    database: ENC[AES256_GCM,data:pz8lfntD4Q==,iv:TMP0WBG6MCSouEqJEXUd8zYeR8r3WW3hsfl/4YcePOo=,tag:JbHPJwTW5Fy7RCn9RWr8DQ==,type:str]
    externalConnectionString: ENC[AES256_GCM,data:0rdOgFuGELWeoRtarVVeAccqh4ZiOqSL+LLYkOCsDn/YlDCPoFCR9yyW+xZRdvSdOOjczjxBjmYqj0R0OrRAqZ8HSqjXrOAQf8wU0Mg+s9pLQLXjOIUnj4Wxt5k+FsTlZ8s=,iv:3Y9V569PrtMIt8W00pej3WQqHCsav4YCOjHAYyFyhxo=,tag:AoluzABBvG+j/GJJ2dpQLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRWFMcE9Xd3dNR29wQW9a
            TEFCU0E5T2U5YTNNMElvRGN0a2dqU0R6a3lJCmUxRHZ5aVVGOW9IQS9Sbm53anR0
            MGlkdW4xOWw3c2lYN2kzSFJWc1VORDQKLS0tIGxJNndNaDFZRVNFR2U4OWNCMVla
            dFMrTGZ1WEpndDBUaDUxQWZRbXhFOEEKCZyPdAIshIgsJAsosvkXpt/2n4bRVqvG
            Zx0jEcMYDCBtg5HNJskbKtbEDX8lHprG34A2jMBzbA9yWLh9aa751A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T10:14:00Z"
    mac: ENC[AES256_GCM,data:0LeadMKM+MCmg2L6zN7lAkwL8NWoQRPyur9QqOLqFwTtujgS/xQS2O5x2QvnkM2HMO38+Mk3Ot0HguTp03uHqLrJaSCK1hqZJmUP1h9hCnam7nW2ZfylUsVsfGOgTFBml42NLdBpej3AzdX0DnvdaAj/pIIEa016+xcjrB6RDVM=,iv:9vdN+88lfyZLID2Ta5uIj2s9htsh3NttFPHYhJ29/ZU=,tag:TblUpqajTGGCfp4jfndpEQ==,type:str]
    version: 3.13.1
