apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-credentials
    namespace: llm-hub
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:W7E8qeRpdQ==,iv:xCL1+lVeL08o8GB33TUB0OrWy+Dn01+L1l3e+RJGcV4=,tag:oxmySDVsgDh+/cNj2uKGqw==,type:str]
    password: ENC[AES256_GCM,data:8Z0gBcSYuXwUBr6xzLh0PUUIasPK+aQO,iv:I4s7ENpBf8fUwUYh/KdsDqNKV1EfExtordklLBm8qQ8=,tag:3hOU1+PJZzFo5gHtodeaKQ==,type:str]
    host: ENC[AES256_GCM,data:zMJdidnp5CayEg9RC5jrvT3JQ7N2fDSq+Qv230T2ssgORZuvET6/,iv:wYu9JB85CEFrnk/9WkqgocfcFJQuvPm3RRiquqWq044=,tag:lgh20kTo0grjIlAGZ0wOFQ==,type:str]
    port: ENC[AES256_GCM,data:MBRk2g==,iv:E97xzsM+XvxCjaifEDtP57KyWZoT7A6B6hIbHpRPjDU=,tag:aHT+lAHWC5dwihXmj26dzA==,type:int]
    database: ENC[AES256_GCM,data:811HY9tzwQ==,iv:x6LgzrOJh9A3ZnFAgHVEn8e8JX3fIlEktfnx2XdNljY=,tag:u4ZHfYVP0MbraNQmRejJYQ==,type:str]
    externalConnectionString: ENC[AES256_GCM,data:TNsPWW//OoPHbOGwsEL/vnS6qw8dMHcMIrEmkSmc0yJ2cZ0KVsnbGRamHg/D3VlaEg1bAQ/yXpoeDmC6agNyeTZeb4XBsChAg68mAzmVrlgeWn4ji1WtBx3bQOrJ/6VCDPE=,iv:H7EFBGUo9f14GUT7+k1S6ILaIOnwgnPJ9BGYxXN3GS4=,tag:BtdO9U1Sjsyfh+BJfLQMsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueU05MlM2R3l1RGgxQWlZ
            TDlRN05va3RTSDQ4UE5rbkt6SldlZktiOEVvCitTM3grMEZXMWVUVGE0Mlk1WDBC
            Q3VpMW16TkxHY0ovT1hqOGZxOXNYZDAKLS0tIEhlMzcwdTRKUTNNYWtwQ3ptbnpx
            Y0FOaTh6VXhaK2xZYmhTTjNzTU51QW8KDahhx0VW/XUv/Id/n8cBIWtRTBm78hUQ
            Xy3RZ5jK36A8JzPnD1LHf4x3fLC7gqNjoOn5H0sOLV3X9nTY3BumZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T08:45:27Z"
    mac: ENC[AES256_GCM,data:EAPTbsj6r0Kv3sEj+TeMo44SNb0Y/M+uqXwfXNsTh/TR0D7CPArd9MiULOm8jDW7xl7sH8wJkKwdNtNMOf07oTDc+DuQSNOED/mzmj1C5V0S69SaHFumgjtbTksuoFwwPcXitSyHrVJ6MdqvPW2a4gnFADRycCLHsKbt7WzgSDQ=,iv:h298yJOdLLpy1+FG3YzUmCQkWSbUfjitx+GedAJLoo8=,tag:iYccR/zo9iUcINoEIG8NNA==,type:str]
    version: 3.13.1
