apiVersion: v1
kind: Secret
metadata:
    name: litellm-user-keys
    namespace: llm-hub
type: Opaque
stringData:
    wojtek-key: ENC[AES256_GCM,data:+EtCfgmI94+nOmtf0Jh6fnb3u04JkZqxng==,iv:pECC3V3TFmtTm3mGPmfqplq/SKorc4ZB9BU4L1OHcec=,tag:ccMSpk4R9bS1Um0Hb90mtw==,type:str]
    wife-key: ENC[AES256_GCM,data:/tQCI/MDLQvG80mqHwcZh82S0g61mLC4Lg==,iv:ym6FBLGmV78tcKZZut6k6ujJFli5rl1AJlW8DjVmodU=,tag:0aWI5X5SrIOFOyxGzk0STA==,type:str]
    hermes-andrzej-key: ENC[AES256_GCM,data:jF51UdLVvH9k4W4xzm8GC6+hu6pH6dNRHQ==,iv:Sz0HBiwpKsUSmwZ/NIkqQXdKdWl7+fv3V3ZNDbCAivg=,tag:saVkwhnE2B2nAg+krDiq1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SzVEbWxWUiswWXFWS3Nw
            VTNTTHpqcUZkYjdscVh6R3pHS2NNcHlMTTJvCmZXK3AyMnVNYmhhZFZJQ2ViTDZu
            b0k5eE1PeVVOZnBOWEVNT0Zoa2ZIT2cKLS0tIE9NYzlhd3lpcEdjc2tPYVBrMEVk
            NnFlQlRqbE8xOUhFaDloeFZ3MFBnS1EKwPHJm8rpkqLkzCOlZrSmYgdQzbPa5dw9
            uETZX9+QxEGoFmllKFWO4iiuRIsKTJoq+INMr5DEbYdJ9t5FREmHdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T07:29:30Z"
    mac: ENC[AES256_GCM,data:q/4Sy2vuie8OS9TkiwNg2QdJTmsZz4Ox6k9jpg+fPm5btDpMCtwlUhkQMwp6ANYZBpeKHl8sn29m+8sEW00AZSfi0Qt326C1/oqrsRnV80cmV9bLs5lIOuY5xgu5rrBsuSRXUhRUTSRCh5FDP7N6R9YaLcp7ybkruQXz8d3Yptc=,iv:T5R4s9GTQ9eYipeazC9dUZrFhxyCDYmZqg9L2+v3648=,tag:VHb0LIUfStZwwKmoAhK7MQ==,type:str]
    version: 3.13.1
