apiVersion: v1
kind: Secret
metadata:
    name: litellm-user-keys
    namespace: llm-hub
type: Opaque
stringData:
    wojtek-key: ENC[AES256_GCM,data:Rvgob66iUCxiDxEN/aa0xhsURs3YcuwI0g==,iv:n6XYnsnbGq46WMLUctjWt7VNubdYokxxUzExE6aYi54=,tag:3tPkg4tKknvnMvXlwWqsvQ==,type:str]
    wife-key: ENC[AES256_GCM,data:8DKBAvyOAMgznZVUX3EqOGIzhDr2OFxxlg==,iv:gaNVnuSdGK+8WX2uQDDBkKOwGO89dldJCHkU+1HcVLY=,tag:XqrEJQBkt8BCVPzoLtDFew==,type:str]
    hermes-andrzej-key: ENC[AES256_GCM,data:ZVjbvOhHMFy0/OozFvDv9epGbm3pBDYtgQ==,iv:LfJEclbfHjg8SaeWR6FzHOaLmgdGC0BJcwMevUDYu+Q=,tag:IJQZY73HrjRnwrKFPZevMQ==,type:str]
    memory-honcho-key: ENC[AES256_GCM,data:tb6QklQgpGAnI26MhLkCeNsasvAYHACc9g==,iv:y+IZPo2B6PUfPmaEi9/UeRkgshQtJORvRm0KXivC9+Q=,tag:fG6jH9GhCvsk+aKtpPtiHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeXhzRUlkVDEwTlMzU3hU
            eDZGTjZBZE1aelBkdVV1ZjQ4WE1aRU9NVUUwClozMG03cEQvWEs3SFJtYjB3MW1V
            ZHNZc1BXV2hSeHp2bDIzYmFlTzJWSVkKLS0tIEUzeDF5Vmt5c0I3T2dUcmEzNkJ5
            ZmtycDJVRkl1MkF2M01LbnUwRFBzSDgK+k/xnbLUCTDw2VfT2PuM9/q7E3FZrS3F
            8aEWpbrxiedXEw5YP68g/tY3niLu8YYSjqcyMrwk7PRVWyajvIxqUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T07:58:51Z"
    mac: ENC[AES256_GCM,data:4cN6UjITG5DCEb8Va5IhuyZvyoYKbHQOuAXMWjpcOuxmYvvk/SgXDuxfa+i04Q/zUBS9xgFsyIDF54QJddPpTaw6Uw4dYgxMA9WaRGJLEZqqRGEy6IcEwtwDroMVdAB5YqKfVAO8lEvRMCJig/RdaZvF/OyvOfnB0iWhY6Nu3V0=,iv:EC6uhV1UaOnFbsLqsTQdIJyTkaA3i6S1T4hYGqHt+ng=,tag:AVDZ7xKHt2H9sadz7uNhyw==,type:str]
    version: 3.13.1
