apiVersion: v1
kind: Secret
metadata:
    name: litellm-provider-keys
    namespace: llm-hub
type: Opaque
stringData:
    OLLAMA_API_KEY: ENC[AES256_GCM,data:LAxoansR8/1RLkUAjwIOz0A4mxMeJZP/yd+h9tDPUQXyRE0jnWRmKP4Ed7ZUGtdyR1ksr3YM5Bvc,iv:7GlkXLnUkiS57lANbL61ZYJdWQeU3bUG3Nl/9+WZN2o=,tag:A1i4ilJ/xI/nvjbC5SdoTw==,type:str]
    GLM_API_KEY: ENC[AES256_GCM,data:4NW/XQLv9ll/5Fl7eIkokbsrNFdleoq+1/4sE9z1Y7CEScUloW3DZpSgz7eRXrfOFw==,iv:UTqf+MwGN/g34TJZM4CD0qEST30KpigAhlYdwWNRaW0=,tag:RGZaHjn/Rh7cOug4r/5mjQ==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:0TbcKQov0eFrHZ3/+PJeEcpUCqZoLpPE2cTktEzpJlo=,iv:vDOkLP7FDQbpKHgZW1zCHlzydHPiAeccEMuGnWB/Iwk=,tag:pg3RXn/jsQBr6XhESjKmoQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:ryqgXrCcNzzLGPMrtANsr7Ye74ywD5Ikc/h3I7yPjDAqu0nFmPNaEamTwSZbfIAxdIBmMj5G2DCniLNkyXGgiDK5WDaPQA37Vw==,iv:IlZRm5zZSyJqy3KmRLzOpj6t6nh9HpCRW65a4xIKwDQ=,tag:KOOtmHnu/thhl2CqnV6IuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGpTOFFOMitGbkZnQlJY
            a2NLbWs5bFdwb3pNaWVTWm1ucEx3bUtrems4ClZibkxkcklFYk5OVzNpTlB4Z20w
            bUNUYkNjNW0zRkgvV0I1dUg4STJna1UKLS0tIEJJWXBidDBRNnFDd3dPN2V2clZt
            TGtJV0Vobk01Y3A4bUVqU1BrOXVKT2MKC0yBgOfjZbYz/4y/3c6X+b74rN5B+ynr
            IxqepbSEHf2tfpnNZYr/3Kf7Mop73ZWVTIBzY1Krq+3ndaPpjNGhmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T18:02:10Z"
    mac: ENC[AES256_GCM,data:noDRN4uEeJtJ0bondshEyTEAL4+oOhT/msQiN9RaAf0yckmTHGobDkLs0IoqncKlfH81FdfwVVxNTmn4ycVYc43Dxce1ElQk2AzcHSVL/NiZSPVNY8Xpjv19rJCVw9r8MXc4wlGo5Y+8Rj4wKRk8GBrTaD92cx5MPgsReBw2UpM=,iv:/nJqkJoYWVAlBlC7XFmRm2fTXWRO3UEmmEeBtN76BrY=,tag:eySePERzShrQGgQfxNnVZw==,type:str]
    version: 3.13.1
