apiVersion: v1
kind: Secret
metadata:
    name: litellm-tunnel-token
    namespace: llm-hub
stringData:
    token: ENC[AES256_GCM,data:qi+xV/+qMHxlB5xtoXMf+/+HTWLlbOaAbQcFEEx7L1rFxoez38JDabEeQT5Kbkzu9BfckvkRxdKQ8ooJMVOYuMZS6jN7WrJqTCOqdVzNBC0VZ6gK0c41qxinM/q3C9MuQv+kBM9CYgkMphw/6ZsGJi7XKScUnQi3Em2VMXYpo3hUPK2MlU53TaGLU18AjdNHM47EyTzcnbR2wKnWCCgYx6xFGJszOXo6pKQ1UrubB1Ufc5ZNF60yug==,iv:ZFh8YNzSBOQ4IH1feK9Yd/4mkFdpGkWe/vPC2OrLpFg=,tag:2TfReTN4SM/nzpIBKMxzMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZUsxazBJeTJRVmp2d2hn
            WVR1SDVvd0l2by80cTY5eDlxMjNIdC9oeGg0CjZPZE1Xc1l6SmRJTFM3ZUxuWklP
            RWtQSks2eStKUmtLUFV6WURBQ0x5M2MKLS0tIFp4dGptNGdyZFdISlVxTEJwejZS
            VlcvSm9JM004YXJFNDQ5Zi9zYlR3TzgK4lgzepP+6JeZPOQ3RTl9lxjtrKkK6uHa
            Ks1z82Qc+SqHQ2xkMe+8e3ZHQqq50Rpu1NDdkMcD6c3SFQLl9cUTFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$$
    lastmodified: "2026-06-24T11:16:44Z"
    mac: ENC[AES256_GCM,data:6BFUP1iFMmAPI321lFU6l8tunEzE7IwJlvgt7vqCtbRFiqWciVMZbBWq26b/1qUoLgzyACDwTYpD0EhgPecgAQX2OZgSJp48MlwGefoXs9UJykgMbp93siSWXwLzYztpjsFbtDontvSSTQON9TnsgBunlM31D0Fx15g5K5HqT0c=,iv:2eY2DbXjvK5Cte+Li8dADSVLHwT8AVOP8Sv/4DbNyAI=,tag:640c7XMhLUxjzHUJwlqZTQ==,type:str]
    version: 3.13.1
