apiVersion: v1
kind: Secret
metadata:
    name: openwebui-db-credentials
    namespace: llm-hub
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:q9VrEZoQSpu5,iv:5WK4e/RSTYWSyXHo8ud/QDu84TEZgSsbzkRQkaUzGRk=,tag:k8nZ9o+eOHaE29zjtPD0HQ==,type:str]
    password: ENC[AES256_GCM,data:YbRzNu0gnYkSWaQPaI/VgEqBzwg5gsLb,iv:nzknS7zFuYHvADqb9uHpwdPEqoBKHMV5R/AOVPTF0ZA=,tag:k3dYlZb+mnuWEFBYVLDSCw==,type:str]
    host: ENC[AES256_GCM,data:JIQzKr0En9aUpsozXXqZes/5WHMHQZ4hVxX7vAcVHD4xxbjbgJkIM9E=,iv:L1bO+iWtLJiUIm7+vaZufwxRPMmp38cJCX1HCX/8EOk=,tag:4Mq8zEsoAbwgJfI1TWVjRA==,type:str]
    port: ENC[AES256_GCM,data:yLYEsg==,iv:kJRkaqBlvu5r7YAW8tYljBm59jxT2dbs8Ih/b1YItHk=,tag:AOuLDaRgB+aNDGRgd9bvxg==,type:int]
    database: ENC[AES256_GCM,data:AApXFJ0f40gO,iv:Lt1VupNto+Lrm020dRs0DL2adJhwQOoYHq4ujhuWn0M=,tag:8TYqzQFp5Xv0wUCya3jY3Q==,type:str]
    databaseUrl: ENC[AES256_GCM,data:OPOR+Gpy4/Nu1DjM4LFdy0QGrLPcf7qV+rq7i7fzfbHvgNDnfb2yvLGGoSz6D7s5SljpnXDnnODpPfo/sHUN1yKCiGTZCIugNj9Pp8eFRfst7TtErGDqLmIhjIokn38kqCrHpSpbpaM=,iv:7rRkIG6dgG7fgby2SZunjMxk+3z3Qe/VF781NHLNoSo=,tag:7drjTSGdsPVpIknlPTeLwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaE1ZSGlHeHlVYmxSK0t3
            R205aEpsTVZncnVUUlZZN0pwQ0l1MDZmeERZCldWMFNURllEQ3FlbjMyUSsxdkwr
            Y3dHTU1zRmN4bitIZnZHQThGTVFKUUUKLS0tIE1MNmtyZlJDc1hHWTEwRW9MQWRm
            Ujd2dFp6OGE5SEZqQmpudHU1TkRpSG8KxiQ7MqST0HKXnaexqzB5LuKZnONuIJ2k
            d/HAAoVk99hNAfzOHf0qGv3OIMQAHZNY2nwvcKdQh3pWrgCDaQ0+yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T08:45:27Z"
    mac: ENC[AES256_GCM,data:VhW2uTze8CR4F+UeWSPTSnmEWIQYgF7ZrgtoW2iVL55u9v1d+HTZvKXkAuyw4giywXynQOJqJIOr4bpn3LWd8/KskH1qK1uBRfDJo4r765oPQtmLXhHePeb3gIytcaYUrzrVkJ5gCfCDpENDG9GsIv2WHDAeRUGbfEqgpyzYfcE=,iv:IIKjvTzLqBFh6P2E5B4hJOFEtmxuiXt16bacm0IWZec=,tag:gvdCtF1C34YUiYAFhyD+jg==,type:str]
    version: 3.13.1
