apiVersion: v1
kind: Secret
metadata:
    name: openwebui-admin-credentials
    namespace: llm-hub
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:Wb0koDYPdYWje2LBvWa8LxE=,iv:1BoSTbGsb8rYDNur/Y+xsXcX9lMKv/L4bSHgjbQVZss=,tag:fxTflVEAyTlsK8bruEh5FQ==,type:str]
    password: ENC[AES256_GCM,data:I8c40hEDVTmBxqf/LFHIecpFXi0UgYCt,iv:Gm418TDmrzVq1Lld83GfZUS0sdPNS09jJ+CdqVdlNAc=,tag:5M8hR6ztyOJCzxFE6eNxLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS0RjaXVCVThrK1FhSVpq
            ckZjZ0diUGJleVNPd0FwVHZWQnZSNXZqNDM4CkZYTm1aejJBUEJURlE1S3N6MERl
            VGRucXFtY2lnYm5jQlVodnBlUmpma0UKLS0tIDVyOTN1TzB4VWliZmkzMWtOSjNK
            WlhLWWhHWGxKU3hNVmFoTW4wallCWFUKndnL5PcvrfObZ5BnJ3lJ2ZUA6ZVT59OW
            9rBdNK66frzLbHCaxYLM1iTjSY+PQ6zekLw/wB7plyALw5+qpXy/bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T08:45:27Z"
    mac: ENC[AES256_GCM,data:BtVU5BDlxQZAW8e5bQmQzEk7oOz2Q+9clSWGm9oZV2wQhH2qBfF2Jdlh3jvjikh3Am8u7OzxuuXpvVovI9P4mreiMIQveskt8bg7voTqHjxMK+gVWPBlOuGrTQmNO1c6RdiXeyMhcK0rD3+GoUCNBRqh+8alJoNb/2wdQq+WsxA=,iv:JdvFn5FGNzpaEfokl35+e8RsStxwG+09L33cJLzZneQ=,tag:qjqq26N7+iouazHDiJwLwQ==,type:str]
    version: 3.13.1
