apiVersion: v1
kind: Secret
metadata:
    name: openwebui-firecrawl-api-key
    namespace: llm-hub
type: Opaque
stringData:
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:03hvkIBVTGnqxWO5Fd5BtPFP3kH4R0PxMbZmoHGtrkkyiVmKEGaPPV9ul8EAekMPSsLCzb6XH+WvX2Wwo3gl1w==,iv:GXmujZs0rq+apgZEI3P5r9ZNQmt0a4/g4ktdhgNINIg=,tag:6Fm05mjjAM2APcQDHZ+YEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOXBnVVRWSUYzbS9PcU9Z
            ZnZqREsybndPYnlDNVVpdVgwTWdNVUFScmpRCjViaWozaUxYWGh1SEJaS3ZjOHpS
            YzcyeXBuZTJKT3FpOHEzY0NTbzY1YlUKLS0tIEI4d2ZmUGN5YXd4M0ZUWUxYUXlT
            am93Yzd1cWRMeHFKckpkNHdOZHZOSWsKyHMHkWY6mxgF8bTGfH0yehYlYiUZJaUd
            HiXO5MNQNJnj8HpMuqdduHcwWSojhFZo1fzJE+Hh0EKys/pDu66lgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T11:52:09Z"
    mac: ENC[AES256_GCM,data:ViRD38Y2YpVeI5GVhqoivXlyX5FJybzKh0DIirPns5hJ1BVFaQfHIJgHCdGr9lx+itQC8D4Px5Pv9CUVvDLL/x8mDM9DvQ35z1/7OAIPkNlj3HLyI+O2BLknb9QJiptUjpgjNF7N0PrjsQPy7rhxMPIoAd2rEwKkpO+Nhjo2+As=,iv:9uAfQ+LGI3sNHW1ce8hizPElr+RPsiy7/YJQ/pzH+Zw=,tag:plxI2vBvZLRS8+997OwFWQ==,type:str]
    version: 3.13.1
