apiVersion: v1
kind: Secret
metadata:
    name: openwebui-db-credentials
    namespace: llm-hub
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MOYOVRuEUZ9F,iv:t8YW/PdAieT2kWSLlKAwtvvTV58MZB1V0XZ0mX7NadY=,tag:z1l08PzqsluKd6mOFvDQZw==,type:str]
    password: ENC[AES256_GCM,data:w4JMp/jqdpgS3epBk9lzft3tD9BxFzxK,iv:8cBKBtQg+dLOsxINWN9maUWVWcWHfRAFPECEdOLFZkk=,tag:LSF0WZv4GMG7932HhzeCRQ==,type:str]
    host: ENC[AES256_GCM,data:emNcyIkKLory0e+1vLv1I49NiXORUaWZjMjohPboUXf708ek+/FqjeI=,iv:A0mXf+oPl35lW/76RPDiykgVblXdEBLRH3B+2/3jnH8=,tag:XbGWtnbBaBAlOLwPOKDFBQ==,type:str]
    port: ENC[AES256_GCM,data:cDnpsw==,iv:7vikzC1OfX2Z4QLwNmvR5boQZUj2ZI7dD9W8p8yB3Po=,tag:qQ0K60FR05qJhx/lBrkv9Q==,type:str]
    database: ENC[AES256_GCM,data:qZdzMNp1YSfJ,iv:CoSWAERLaT1szisuiNizA+K5vS+zBgOIRvQ+lCb7ZuY=,tag:fDHkK05iS60v79CL5HV3Xw==,type:str]
    databaseUrl: ENC[AES256_GCM,data:Ndvizcq1u57QOVu+7059WyIvKamgBuE5aJ6XYzBLn4FNBE0k8/UChVf06KbVdNRaEUTSjRwNGEp7J0bIlSwoFNNXJL+D+QXUtMpHUO7y8fN+G4t/oZEFjVCajydCHCKam0P8tLDf5X4=,iv:aFKyzp6m1iUId3mErjUeEON+oJtwTQVK9gyMDfNTzCc=,tag:mtvsxr9ByLxBJVfkZABFaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM2dRbDNIS1p5aWJZQlpt
            SlBMMmdjUUVFQ0J1TjdvQ0hTaGhkem5sZkNvCm1ZNGl0eElGVzR3N0JTWGVORU10
            MzFCSE1rOTUrdzNUNVJNOEJHQk8yZFEKLS0tIGFwbDJtRFB0WDl5SWdpd0czS21n
            azZyeWhYb3doTklxN003elJSWmhMRkEKPQQqNEisygETwE3N1Srt0U+l54j6LL0V
            4WECEiFH85VbLuOum+xzVPNIMWgVgbZPeQHImMO6cFh3YGyH02AozQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T10:14:01Z"
    mac: ENC[AES256_GCM,data:TJEvO90Z8WLhanBGeYGjolg62e3CcKiC3As0o5SFpJ/9CkFOS+FMOPf1EyjG6JgiW0apgig7iJ4KIweYFW3RT4ZkqbfOq8Q8zsJxGbZwLT1sFNFxiPPfVyo/VVKP9hiw+C27SDQpV3pvxyBDQATYM8Q11k9kWJnwzzku14UuVs8=,iv:eydCnIioRAs7RiaD+oBxDxqan+87/fyh6Xmg7H8f/c0=,tag:pn5gEh/5/9BjKNHHvUFVlQ==,type:str]
    version: 3.13.1
