apiVersion: v1
kind: Secret
metadata:
    name: openwebui-admin-credentials
    namespace: llm-hub
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:KCn3KBSbkIgSxDJ25jDVetrDUmccDGo=,iv:zvM5xCC51lUFBVQbQqe40M3asXuaa4/x7CZZhPNSe3s=,tag:AdDica0dwq44j90RB5zxmg==,type:str]
    password: ENC[AES256_GCM,data:W7TSKNQWo0sAssOPQVANkpNC41y/au7h,iv:CpNfI5zQkYD6qvL8hebkFEA2zU0Dyfz9zqMRqRrk/jY=,tag:jhhLWNxKfMxjhYaIL9Ry5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ejgvQVBmaXZlRmsyZG1i
            WUZiT3hrbVI5Tkk2QTk3R0w2emRLaTNZV200CkdOdDk2M3hma241bzdzczdQTVpY
            NlFVTTc2VWExbk1aOEZjV08yTmRkN28KLS0tIGFCSW9IcjJhNGowSmdDMmhibWUr
            Y2ZROWVuSEgzbjNEYTJHNE9FdzE2ZE0KyWglA823+m9qQGJwymt/awEqDElRhqma
            7Ga9hzgfdWrqXMW7z97Tt8Gxj3CHgE+Oz+hwl3dAEbkEvJBDiUNpOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T20:21:21Z"
    mac: ENC[AES256_GCM,data:KxHTcixysaxhhB4QOLSm+fG/jqrCw/YyYGi4Ch4K+TjkVWkg9P9gjjNy4w9I2drKx20ykIZX+5W9fw1yBjcZoFkX3sqhg+W7iBO3C6XDW1EDRlw+Klnd421W4+yRjH8xfuS99ec2rsLz4Jv/gBC4+JrhLLJY22rfX76XErhHnkg=,iv:PhdNTbxGlhNglobuAArocrt997Mi67SwpitC4H19vEE=,tag:APW0yFf3t93UNWyNUyK31A==,type:str]
    version: 3.13.1
