apiVersion: v1
kind: Secret
metadata:
    name: openwebui-wife-credentials
    namespace: llm-hub
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:7vPW79B9bv9GeGs9kJPVCA==,iv:WO+7fFh2hw5V4OWNuHWyXSLxzgi9po5eP3XSPPvuCUs=,tag:WjInh4+XMWRieY89FAcSxQ==,type:str]
    password: ENC[AES256_GCM,data:grK9Dt8W2mV7OVDJekAXoxZ9HcLjAd0zr2HF4XJufXSj0vk=,iv:AjfJyb3jxLnewR5fzCZ27geK62e+3LKxXJb4WYXXU38=,tag:xBbc11D9PLYaON/ArxP87A==,type:str]
    name: ENC[AES256_GCM,data:T9BJ9w==,iv:yRa+0TPWe4v6/COoqoy/GM1ZDPfeJOEjrOajBtxus+U=,tag:PFLCuVMzVfjWvNfAeM8Wiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aVNKOHRMZEFlbFZNK2M1
            ZCtSQW9hVnl5T0lIMDVrZ05nK3FLdDFzR213CmVDV2t2TGF3N2hicnZaVXU5NElF
            RzFMTEdsc2NVa1FPeDNjaVRxVGJBem8KLS0tIERkYWIrakttR3M4WDZMdUlsYXhZ
            dzdiYVlpN3ZGMFRoYjg4WlZLejcydFkK1XdkTaiWGgFJbSVOTCDpxtuRxcmg9rM6
            p0EYn52TexoAFZ5RUpZZQnEjNY4ClsgW9rTo0Lw8HdFIkQYG8nCh+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T15:49:36Z"
    mac: ENC[AES256_GCM,data:pPB+03+RWYi6i6VIZAum/Fc62fh0UqGABvpAuVP+I0QJ0hyS/twmYtvCEsPqIHHpqKUSMREEMxgWhGVumRy704PjAhyHQAMjjDgD6ntBNtlALBzQKxWqv4JnB/Kav1H5ILr35El/rINfGTNleaFusRz2V0qZfjrYbNhS6JG3Flo=,iv:frlBlMwHxLJ/bys1WMvW5maPggS6NuYWE+erTeQB3Fg=,tag:6xN8itj7A/0CFwsjbsEzEA==,type:str]
    version: 3.13.1
