apiVersion: v1
kind: Secret
metadata:
    name: pihole-app-secrets
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:I+M0l0qgIGdApkjQumXeVB1hbY3S67Vp6ilNsjhiyCA=,iv:2HtzKAM+ADABOSo0pI9z9TdCz/o1VPM2IS7Z90pmrIw=,tag:7oEpF3IiVjSL0PwQ1cSixw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVlAxcGZvTVZuNkcvZmI4
            ZVFjTXhOZVRHS3ExeENnNnNDNTVZTnZNQUZRCklJN3JZNU8vV1pPeFhDQlhrUWsr
            RFFHUWZlOEJoNXE3SFR1MEF0TmVEWmcKLS0tIHorMy8rdjB0WmxSUXZKUjIxRElY
            eGI2ay83N2xvMDdXWTZGaS9acmpiK3cK8G5L0NsrtRq/MtOjIQJ20X7V6lih4OpX
            DSM0FMtU9/zRzByrDLorqlX848tlDPlouAwCDV6UrBeMCH51RqgXUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:58:56Z"
    mac: ENC[AES256_GCM,data:A2ijhUgT5IXl/lP9PSvuhJfUWfClPM7uOpO2VECXrCubqtu5bWpRmYk4bZ8RIO7JdSEyExB/aMTRBj3zByFgXdy0OrSBKKy/ooB6W5qTzuoREOK3FjunCvehOZ8BWwfvoSM/MB+VRKTg3W0JqpCDPskboS7fHm7lI7+AKQlehiI=,iv:YcAs4GatwN2xCsPPm///CMO7wRdtv/eWELTqq5K7RiA=,tag:k/64zMYyNoku5Yn0ag6uQA==,type:str]
    version: 3.13.1
