---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: firecrawl
  labels:
    app.kubernetes.io/name: firecrawl-api
    app.kubernetes.io/part-of: firecrawl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: firecrawl-api
    app.kubernetes.io/part-of: firecrawl
  ports:
    - name: http
      port: 3002
      targetPort: 3002
