apiVersion: v1
kind: Secret
metadata:
    name: firecrawl-api-key
    namespace: firecrawl
type: Opaque
stringData:
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:IddBY6dKoc97U0gLvUannZSzxmq+QDn2yVoON5LpmdZmpARU02M7chtR+e0s5V3klhwgqsX0GLzP3IZprFlepA==,iv:dl1Mp/Ajf0XSzp2KEFZAlSEibX7sGjjsJ2iMbK/YIDA=,tag:WRMvJeoKwGO2TlpyCDnN8A==,type:str]
    BULL_AUTH_KEY: ENC[AES256_GCM,data:5WkQ2cHpNhOOCUvuZp93iaJKZxJzj/S+4tfTmPqidN58XedXaASlP4+K4JKEE0QYTSWSWFLGOqQiJhZ1FiJ0Pw==,iv:iIOyt3Enui+Kt3ybrPsUL8GR04J0ZlNnHifZzz21Kp4=,tag:zME78VHbmXQIW9lt8N3Qsg==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:QAVqsgdkkXCndYGsvWAYHRih3MkajsafT1jGgv9hBd7ACZJWolHs526m4w==,iv:Vohvs9jQVc/nB3DUrP+XXrFuK9rvXExNPJi37R+ne8I=,tag:3Ryn9zKt+S6eRIi/98VJhw==,type:str]
    NUQ_RABBITMQ_URL: ENC[AES256_GCM,data:1H8xaRdsVAiVWessppamCRrFYF8ung/OfLUQRgjeFucm1hxfbUsG84ql/y6GorqY6Bw44p9LEk6v8ywlC6AaIw/r1VGZ7R2xuUI3e89H9m6JyOUZlEbeHXE0HhYIX9adwmMpjjQy,iv:3itegypo3R3Sy/6aVFAAxFmt2xQ8QfoNheszGMTL2Fs=,tag:9PpCJ8DHztdHr+RKenJPCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOEt1OXk3aU5aUXJRTDEw
            cUdCMlpiN1RDZkxWWS9CMkZETWQ2QnZQRTNZCkFpaVkydU16dHgxZGdUenMvMFFv
            WEtNZGpYeENrcCs4QW5MSytSOFJLaUEKLS0tIDJJUjViNExqZU1Bcm5DYWVINmg0
            MVJqN3J6N2RKSGt2UFZwcFJCUk9KbjgK3adQjiD5lVJle/dkb7AcNC/yv4wVnWzc
            Xc1QpZDB2AeCHWZtmC5V1nlM7I/gH0mo6AOxlTBceoZ62SRT47YgFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T11:27:46Z"
    mac: ENC[AES256_GCM,data:UQ6B9SAOwsofa9bxdgCnh8ZsuJgJ7IsgM9XtQxmtuVEiy41lkC5yWZJxgX55zu3sKxdWBRzTl2EDOBaZvdFmxTxNnBJEINjKwv3+QsXlCtglGSyAC5LS9R1368MC0O+25OtnBm5XX1wwS/vZegT/jeYyWzsQHiT8lPElyvdyBAw=,iv:6dm4Tm1vQzETQGqcOU6/LKE7B0VQPISlvnpByRIBqOA=,tag:t2L/Je7Ec8jEr9vdjMSD5A==,type:str]
    version: 3.13.1
