apiVersion: v1
kind: Secret
metadata:
    name: firecrawl-db-credentials
    namespace: firecrawl
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:p+bAKZxOt8bI,iv:HxOAjt4HGJUbrhryBDHnyKuYFZI7idfnK2xIw01CQAk=,tag:BBQ3VuR1VlR9N5SXMgeTwg==,type:str]
    password: ENC[AES256_GCM,data:k9TtD5B53bGy9HpwUuAiaIc7pFM+vWtFzwnmCZCiR0syzk4+wBRM4lPBpg==,iv:Akit8kY9XfWII3pwfObDhudUwloBS2x4w3MRyh55bOk=,tag:ceKr08Gkfp2YxTO6rTn2+w==,type:str]
    host: ENC[AES256_GCM,data:0X3zNhduhbscHkVT3IBEiYCVLRF/ACTAYQYr3E5GWXv4On5EiGd8LQ==,iv:B655MKvS4WhxLIhKZcUDccxzDyLA6S817G6qLwALmPA=,tag:YCF1fq81W0E62aBz5N1Mzw==,type:str]
    port: ENC[AES256_GCM,data:QeB1Hw==,iv:on1lBn6rUHe/g/gsWzZ+0QYY0a4IMmsjzPlfGNbCNLM=,tag:/f6jkIB86Hue0tyDGyL/VA==,type:str]
    database: ENC[AES256_GCM,data:/iRhHpEJxbM=,iv:WKg/i643Hxygdc2oqgAq+3djslmUiNYIZxNzE6nPjHY=,tag:0mfhkQRaZ5HriqwEmFhHIw==,type:str]
    externalConnectionString: ENC[AES256_GCM,data:b2iw3cN6Ft7ezETHD617JAe0CtvfnRH8aUDLXtOu3bYQBQbzaShwPmZ8UJv9ZfaIvujL/3da1tcsKJyjykPa+2uo1M7uVBPqWLPyETez4+yGbbKDUOcnxuB1/H0KVyaDVvlFzH2Ed8wil3Tzx747LqEQS/UfLL10Zg==,iv:jpv8u7hHZRI2E9ZH7DBGROIA0nCLT8ktUTUJbIqDQXY=,tag:r9V0J9//MlrzOBFtfp2tGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbks2Rm1QVGVWd1EzVTZT
            TEowMGpJeU1OaGlTb0FqWlNOUVcyd21tWkN3ClRERi9QZjZnVSswNXpBN3oxc2d3
            amtEZ2tpM01TVDdWNlZlQXFtY1Qvek0KLS0tIDlWb1VOdEhkOWRCdkxnZ0Jqb1JI
            b0p0ZmhRaXVXSG1NODgyUkZwVDEwV28KMYK8xJBI9vmdzoW0ODPQeeMdJN5EbSg/
            S5dXQIA6iiY/SpXUG0LzK1jZvF5cw7HvqabGwKFZdquXco9bfdxydw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T11:27:46Z"
    mac: ENC[AES256_GCM,data:nO4DnCG0a0ubQRQJ7vCir5s398YaL2upNBSLwd+pS2h1/hxXIy9YjkLCehS1xW9jwqdqTEJFAViSZ2d4NhXWqjcY/cN2i8OYGUVKWDjRHXdanviFZd8MoU9zJijhgvpZC0A/CGtRfHtnpT5n3mlQ/kTjB6N9L8s7m7mdAouW9CE=,iv:c03VHLE0sERY0czUPkMcD+wIe9UvSJ4riVo/PZap8D8=,tag:kvqGQrqG3nkRIA5b4KqTkw==,type:str]
    version: 3.13.1
