apiVersion: v1
kind: Secret
metadata:
    name: firecrawl-minio-backup-creds
    namespace: firecrawl
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:AskTnOk1ZSDyv+vQLIoJFuA++uNJhNp5LqFpdOQ3gkY=,iv:m0zTRC0gm5T3bHRo8tyC2qmJGdm39AFsw1isrbxqayQ=,tag:9d++ixCil2yLmDU5tZeS/w==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:+Db7OIIvazpsSlGOyRJeR1MQ4YgYz/Hm9s1fRjKJJJjGByQjlPVEU7TuYo8hSk2TPvQt9r9EumrrjPL0gbeS2Q==,iv:jqpT7lr4hPhvy3mhEGUiFMHIcI1Qfs2SbFcGoXbLxhM=,tag:AfPPRQuG5SMs8zVGM7j5Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eHdTdUtnRXlyMUVsb3dp
            UGdDR1J5NGh1U2UvZ1BpZ2xHZGlkNVlIbFJ3CnEvYXNxMVdoVVNjMTZWZGs3R3lZ
            TXRBZzJ5TEdsRGJUMFJ4SmVnTDhMSnMKLS0tIGhYVXR0VDJTUW5LcXBua1A1NFdK
            WTBZaU5TZGVOWmRERi9HVTM3cUVyaUEKtcjDPJZ+Cx5UnFCiJ8MWj+g1Gi/e2QHS
            OzuBeIRLZZx3mNGNEAg/2EviWAtjCr+Sfwwm7hBhiHvPvzrlGEF56g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T10:16:10Z"
    mac: ENC[AES256_GCM,data:t199W5LbxhPufZIaxXLA7IVt/o3zgi05r0X8VaynJC3PwA7q02ytWLW4DGmKfOtfqgnU9yDrup4NZ0AkqH4tcFXbTHdE2X67LbiSifAvzju+g2kbVOJJzroNhTAmtnTFU1To5RK2EW0QFe+p1WKSmkMfgZ09fLF1Tk92+kG+93I=,iv:eMrBr7Ry/Aov7Avop77iCuMFtyww2871HYmVzZHybDM=,tag:Wocp1WlFcQmArufjgPbYgA==,type:str]
    version: 3.13.1
