---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  namespace: firecrawl
  labels:
    app.kubernetes.io/name: playwright-service
    app.kubernetes.io/part-of: firecrawl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: playwright-service
    app.kubernetes.io/part-of: firecrawl
  ports:
    - name: http
      port: 3000
      targetPort: 3000
