---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: firecrawl
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: firecrawl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: firecrawl
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
