apiVersion: v1
kind: Secret
metadata:
    name: status-tunnel-token
    namespace: status
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:xj86+SDf0woC2hsVraGFf2tVGd1KUnIiNSAMysPozqlP/D1pRdsDc9DT/TMclRUtj/4xJRycewhLBDKX3ZZryoLSZrc3nZ859PHyvAYO6LOrvRUn7/p9EaRfuHWEo8416p/tU7i0dWtINeOAjZkAg+cTCEwuuyrm3P73Q7/Wr3g8pTWnyrAydPeyFZqH1afSXQzVNUKyQGxvZQiSVEs55BU3Y7O5UNyyCkKZro5/2brLo73aLt0G9g==,iv:0XHm993v4c/7BnlrwpUeI4K+LNzV2RJ7OlegKIrs44I=,tag:nCyJPgvBAHJ2w3wpyg8rgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdDhpVS9uWlV4MU5ablph
            YlNNb1phLzV2NnF3NzZaRmpzWmxFaWZKeGo0Ck9OMVFHZGE3M3NSUExjaUtXbnhl
            Z0szbFBjQnRHK2RwZU9KRVlrbVkyNjgKLS0tIEdjMHdVQ3MvMTgwcUVVWFZCS2N6
            ak4rR1lVbnJvQ0JOOE05QVpsQlRHQ2MKSMrkIt+1u356kiE28nGsNg1RPjfv445Z
            PWWzhXKHAyz1GuGTrBjT47ZRvmMslS23bCWj7AACodjUOQscPMVgPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T10:45:51Z"
    mac: ENC[AES256_GCM,data:9LLZsOoEmoPFXpEra/5IY3ZDzXu64IKJ7RzET1FtFQOmI0YKFlA3alvBiKsjPXTb0B1jf0H9vgso6MHOPpmgiaDbekOKp4JH2bGpeJfrp7pinkSstnquOEleoqQRPz3KXm2naOekz05WkRTC2yuUsBAn6FuHTwrOAKQyJ6chJOA=,iv:hMV+POU+naUFGJVshUyKLvXhqbMr3mzBSbrRcgPw6/Y=,tag:Mb/H13sUHVA6pCqvhpub7A==,type:str]
    version: 3.13.3
