apiVersion: v1
data:
    MM_SQLSETTINGS_DATASOURCE: ENC[AES256_GCM,data:ngQIVf9esVIfjYgvtvt0gpxZZkFmiN52ru3WmPCNK2k1JX8w/HpEv0TicfsEkjqmu6XSONddmSCk3Ln6JGChjiEAeEqKBu6pSSLsIlKQ6x7daoW9nAINf28rl9fAOEQQnL0eztoGvx4d+Nij/ZgZW4KUmu/oGF1RlEO6pQhOxo9i8qfCp8m0KpgVnQ+LlbMG5C9pxJeKqBgWR3atfzA9Vv/63QCF+wdCkEX5RzlhSp/ELGhZkh5tkxfCjuLq0/5ZOkCVjHse/m5L58odS8rGoSkcU68GmpcruQP86Jnprd8=,iv:FNnpN3RoUt4lm0xKoK2ppOBPXbm28XGeaiWoyEUG61E=,tag:CtjyzrkWxdCy7xE3oQ7slg==,type:str]
    password: ENC[AES256_GCM,data:vLKVDA8cx5Y5RXIazhbQTLE4yS8x75V1TvHUpMuieNiZUuTvn/Vz10SzFyT9pJUwnkq9n4KDxGyYyzyiNAAKtA==,iv:Ws1PAGfTktqCZexC28jmExXOGgxU666v4k8DB5YxukU=,tag:NFRheWhxpWpanGeUzAYy6w==,type:str]
    username: ENC[AES256_GCM,data:ny9yCYJgL18UAvM/5yUR2A==,iv:SWsWfL6QK635/m/oldCGpx2ZbrMOhSARAJ23mm/bNm0=,tag:fAWsVrAk3ThiETowMU+qQw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mattermost-db-credentials
    namespace: mattermost
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNkxtcXVYWlZFek9mVGVm
            SlVkdnh0aHdrRWg2d0YrM0VCNS9UcnZDZDBrCm5lRElnTWJtcHkyUVBJMVczSzNj
            ZGZzdXRXWWJXR1Rvek9aVkx4L2dUTHMKLS0tIHp0c243eURJZ3dtem5mWHdjYWw5
            Ym5pemhvUmRrcVNudG1BSVArOG1zelkK1VLk+MzYiqTHAJNwUxIwZ1XZKzsNaBHk
            vk6uCQWD9RYevwaeMaURGe6Vd/pM5y0hRpPHQQtR5ynYzg4ijizp1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T11:39:16Z"
    mac: ENC[AES256_GCM,data:XdbL3pZbuRIexSATzst4kiTeC43snApusyqM7OE/urxW55VWAMcz391c7vf5BebZkf0NZSJ/dUHlCD6hbuLErnM3Y2mx2mBCwbCT4jYeH7qnFRtbD04MRCI8Iub2XFzMAVfpL9Tpk/c/3Em68LoP/yx9c0v1MA0sR4SEMh8tQFs=,iv:MRNGvvpKafkNdhDOAfDxb9VPn1DqBoT39fH7jrbKSdg=,tag:Hr/PYyz/ARK4JQ6VyBtswQ==,type:str]
    version: 3.13.1
