apiVersion: v1
data:
    MM_SQLSETTINGS_DATASOURCE: ENC[AES256_GCM,data:DhLalcqkob7Jl2geY70wobNpFZP1zfwFW14QxfS88GuJA9NcXlci+0A5gfhasjYYkv4G/gHLBTtlKWhq+eqQAlTfM5ukj78Le0DZQiV1q2XDicY80DSKsyQgLkEVIA+32R2wRCqWbD4NHfI/0rTOVZbtnryDRkLOI/0a6eNhGYLQ4LdNfS3PZRrPd58axHGnjIXpM5I4Fzw0UhAi1jXAWllFGtQqHAWbvephHYHxtsMLM5NgvQPgBfjPQDgTWZAKEiiEfTqMkyc=,iv:Ub2Cqp82tN0GOL3tAoyqB/QlmzpbxsS5fqzPNemedig=,tag:w15Jf1fxlbfI1SpDB4zfQg==,type:str]
    externalConnectionString: ENC[AES256_GCM,data:EjtSsdpSdUY1i14W3Nn3KKSbcSIN8N4sqNLE2Y6G+BMTiGbMUVZQCmm1ibTiJfWRNkzhSln6fQPDvtFbzLVRoZdemHk5C8qO/DqTM1RoaafjQMryRjPixsJVJ3Q3GdNtY3nwyTfXdSQmUXOoik3CXx4mpAP8TqDkPe5XNgfDdaRncHqIoaNx5zbj/75HD/gvsw0GWjcSeXsQxkrYLUdKzD5YZkeHi/WbtPnahxP18pVZu7X/w/raSw==,iv:7UuzC+cKXjlxJwyUuGbiSURxfr531cpGFOY+dVchJnA=,tag:/rFIgp7jXsu4hrdjLT45vQ==,type:str]
    password: ENC[AES256_GCM,data:exH0P+hUd9DCJguEcPciD8onHexbPu3Yc+GG1WwsZDYnD30JXVMcvr6rchgjCz3FzOdcLqOAykuKUmMGupzgXA==,iv:clHng22QwxwIFV6g02M8V7PUE4g96RS+4eCMvh2LCcA=,tag:p7yZP5/rmStRxKIIPqNWvQ==,type:str]
    username: ENC[AES256_GCM,data:2jrgIO7gJ7+RBIG5vYMwfw==,iv:RzSeXRuwVYSrNB67uWTAgB5xZj8kbdEyBR+7/j2lNuY=,tag:HNHCyHg5PRPe5kYPYvl5MA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mattermost-db-credentials
    namespace: mattermost
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHlHclRIc1FlVFdiZmZh
            K0YzNThXb2d2eXVYMTQ4aUlBd1o2cVdmdWxNCmc0SkIwS1gxajhLWkVrcThsZDll
            cDA4M2Rpd05POEZIZzdLdElTWlRWVU0KLS0tIHVveXlhMUduWWRWdXhsK3YwMWJk
            SURIOHA3SGl4b1NSRFRYMmlQeDdMZVkKzbf1OrcrwP1/F0wTHPM4C6oR95kSNnwo
            iN0rowIkh4PIDl7npWX7rpmcwzebNDFDXQ5PbDDGYwFOC9Vqybp+qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T18:47:53Z"
    mac: ENC[AES256_GCM,data:AesoW3ZnizdkCuDtMVwk2MIyK9bop++GjYzYMA1CDSICesal1BHCg2DPnx6lfbtFDBRxTa9in9CA8ob0912jks348OA3qEQ5TBmtabVAmsPBeR+tSxsIp/9duCIHp/LzKg6fpPcNHqMFGrB+DDzwUAeLBQIXPqx2euJ2j0ZSfQE=,iv:aF0BwdYYjoxRekICUn7++rNbSbyA1D7elvFcEySKn48=,tag:D9uihziPlyGMvyF/h+/EGg==,type:str]
    version: 3.13.1
