apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost
  namespace: mattermost
spec:
  chart:
    spec:
      chart: mattermost-team-edition
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: flux-system
      version: '>=6.6.0'
  install:
    remediation:
      retries: 3
  interval: 1h
  upgrade:
    remediation:
      retries: 3
  values:
    externalDB:
      enabled: true
      externalConnectionString: OVERRIDDEN_BY_VALUESFROM
      externalDriverType: postgres
    extraEnvVars:
    - name: MM_FILESETTINGS_DRIVERNAME
      value: amazons3
    - name: MM_FILESETTINGS_AMAZONS3ACCESSKEYID
      valueFrom:
        secretKeyRef:
          key: ACCESS_KEY_ID
          name: mattermost-minio-creds
    - name: MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
      valueFrom:
        secretKeyRef:
          key: ACCESS_SECRET_KEY
          name: mattermost-minio-creds
    - name: MM_FILESETTINGS_AMAZONS3BUCKET
      value: mattermost-files
    - name: MM_FILESETTINGS_AMAZONS3REGION
      value: us-east-1
    - name: MM_FILESETTINGS_AMAZONS3ENDPOINT
      value: http://openmediavault.local:9000
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: 'false'
    - name: MM_SERVICESETTINGS_SITEURL
      value: http://192.168.1.179:8065
    - name: MM_EMAILSETTINGS_ENABLESIGNUPWITHEMAIL
      value: 'false'
    - name: MM_EMAILSETTINGS_ENABLESIGNINWITHEMAIL
      value: 'false'
    - name: MM_EMAILSETTINGS_SMTPSERVER
      value: ''
    - name: MM_EMAILSETTINGS_SMTPPORT
      value: ''
    - name: MM_TEAMSETTINGS_ENABLEOPENSERVER
      value: 'false'
    - name: MM_TEAMSETTINGS_ENABLEUSERCREATION
      value: 'false'
    - name: MM_TEAMSETTINGS_ENABLETEAMSCREATION
      value: 'false'
    - name: MM_LOGSETTINGS_CONSOLELEVEL
      value: INFO
    - name: MM_LOGSETTINGS_FILELEVEL
      value: INFO
    ingress:
      enabled: false
    mysql:
      enabled: false
    persistence:
      data:
        enabled: false
      plugins:
        enabled: false
    service:
      externalPort: 8065
      internalPort: 8065
      type: ClusterIP
  valuesFrom:
  - kind: Secret
    name: mattermost-db-credentials
    targetPath: externalDB.externalConnectionString
    valuesKey: externalConnectionString
