apiVersion: v1
kind: Secret
metadata:
    name: mattermost-initial-admin-password
    namespace: mattermost
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iA1PMAYi1Q==,iv:6PO4Ca3MT4GJd+WvlQbHZcbBi8h2Zu6hYiB4WkXs+SM=,tag:iu14l7wOY0nFlqT4k2a/ow==,type:str]
    email: ENC[AES256_GCM,data:lRjzksg0G0VEglcKBE5kkSKT,iv:rZtie571SQ9qRqdVogWwNUk9dsQsqt4/Nli4KIsdcgs=,tag:FxybV+sUMtO6OIdemE3tpg==,type:str]
    password: ENC[AES256_GCM,data:AJp5yr2BMvLFwVwPhWIPV+HMaufON90WwFzEezou5gg=,iv:e7Uj4qhjdVl2RVBBOEpa+v5yVZwYhYR16QPY8XCZzM0=,tag:/m48WbAK6aQ2E/vOhtPwkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQllSeks2K2xSODJDaTF4
            ZzVtcjRmZnRZTDFrbytaOFBOSUpkTEJNRFFNClFzekF3MVZFaGJydFhsbTBtSDBi
            UXl4N3l0THorbXJKZmtBSWFSeUZBVGsKLS0tIGZyMDZWUnQ0d1FCL2ZiVnFtdkpF
            VEZIS2IzcmwzYSszT2ZwVkVYYlB5bWsKA8AbsSUZpBEWkYz3E0gYRmKZffzytRwS
            j/+JiEeKAQFGpsLUTtRDVaFr/z9h+ep39RQPRug9gpZ4WDzvdmdHeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T12:42:42Z"
    mac: ENC[AES256_GCM,data:+u+1y4hdF0YTPeaW1sKge0aSuAN6avzdod29X2tC5HkJnhIIL16WKcqxKyf+uUaMBaAf/kyyAJ4dsyKHJUPDCGa2faxvhahD9pSAK7yI50ScUeo3coAbgBb2fD0cym9fk9+JE3TmjZvakRjE7XFIxgfg0kmXkkNqkOyqmbmm33I=,iv:2KYi0FLX/V6R7oHaCJRZi0dKS9Bw8NK/FX7rXQNyExk=,tag:ya4gL1WtNXNDvB7NeDBXYw==,type:str]
    version: 3.13.1
