apiVersion: v1
data:
    MM_SQLSETTINGS_DATASOURCE: ENC[AES256_GCM,data:d61kJ/9ypPzXmhjKns/aduF6H283JomdJ28nVhwL9BGheco8VHVviq8YJcs//CfYg0otKpzr6QaWKPo94bzQq2tNeJWVXOVyu3yMBUxxzY/E/ECplsHZcODjr2oBmnojxa7wqJJHC2MKUNLKuAOx3uh4UH7K7gffksLG7byxfXcd18j8RLfyfpSqDOZLaERlVKlVayAGfrLxS9kYskHDoDzrpcNxLAlbrkIQwR0EOYGbdouSRmjnykXGxUE9NjVl25RLuAGI3hE=,iv:jGFbVzDhEQFcKPZIoIKmle0HiCHTmJJ5xPq1U1A9zhQ=,tag:O3YrpXc14+eU4c2RW0C6IQ==,type:str]
    password: ENC[AES256_GCM,data:2StkdoT8M1ELa+B9t5VuSCwhneaFd5dkaNaKe8dXD+al01KLR+VQHoia1T7bi2dBwyDUbZ7k5gFn+H4sMuoqOA==,iv:GCmI5onJCwXy8Tr8sJMEM5Vq5i+bWsdMPNDGuo4uuD4=,tag:NYwk2QUUwJ+HGKSuaBeeTw==,type:str]
    username: ENC[AES256_GCM,data:rZY5JtlwBFAPbsrMWsbBbQ==,iv:3sUm7zMrwsUEYKYnQng/fDzNBtKhnJTpF4GSzyGM/fI=,tag:Pz6fpcY7sDSbSHNrKZ1rNg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mattermost-db-credentials
    namespace: mattermost
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMXRqbnZaTHM3VTB5UDRG
            ZkZxeW12cG9PL0IwaHcwSElDV2t2ODVmTDE4CmNaRi9sczR6N1NCTlFQTXhGbTdQ
            a0d2bjZTQ3lkRDByWms4cmxCYmlSVTAKLS0tIEZCU3hzTGxuT0x1L01qOWw4MFZu
            Lyt5SFp0WklBLzNlbUsybFZFaldBdkEKjNk5qwG/Ojl7CBya6K0hAN72QSRktIdZ
            jDPts7BNd+e/weMYeJ4YKBd6gR7yHrzTJBwqgDNOFoFr2nycoAwzxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T10:39:02Z"
    mac: ENC[AES256_GCM,data:BsD1vbnF1V2jaIHxLiwU30oXJf2NDPQBfV2o3+WbUY+kz3NewN5gNWMqiIWcbeEuqTb28eEIo6oGHMTLeS6WXUCa8aJ+hIj1fJpTxswnZkm6Ny2xL3rqfN4fjY0h3k8N8Bf4QhKEIB24uKyD116bDrhDvBoDxsKic5p8fmfTeVk=,iv:yg2uytNCRUtLw14Tla5bOLAKfE+Ct6yXauVcB6mTOmg=,tag:v+xlILs3tifG5bjvf/OFzQ==,type:str]
    version: 3.13.1
