apiVersion: v1
kind: Secret
metadata:
    name: mattermost-initial-admin-password
    namespace: mattermost
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4aVwVsWoXA==,iv:GhFIks8NzhnxxQEUSLttP1Fa4pIMNqmt+Vcpivr5HmM=,tag:dKdAOw5DNph/4HSJSgXKZA==,type:str]
    email: ENC[AES256_GCM,data:h/mXH7UojkZVj5fv0Yq7/QVW,iv:hBDL2H+jgeZdcyQloImmSISwUqfW5jT4kMkTaYWsNpQ=,tag:/68Hl+pv1AGgbOrVSbfR8A==,type:str]
    password: ENC[AES256_GCM,data:6+af2BGWMEUHODhtfu4rXpDXpJciX/zU46GccXhVemw=,iv:sUXP5tozd8EeERFf7H0wnMXpvow6BaIKK4L9vbn83PA=,tag:L7x4ExIPtDhYUIQGUIC4bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYnEzUU5kcHAreUd5NTd5
            aldMTEVzb29mN2tzb3NuK0pqL3RXc0I0QW5BCklsMGt0NlA2ZWl2ejFhUk5tQTQz
            ZnY3enBoYlM3TW5uallEdXhDRXB6ZVUKLS0tIHVXeWRoWXAzS1BCN2dEWlFaRG1B
            TWhGazdNaVRRdUhIb2IvcHoxNjNEMEUKzrgD69Z6oCTcOXpNnYCNRJOyRWePIyNw
            ua552nbkYuNcqPsIYjsr0OxSO2Ssl5lns6y8bPmMZIElHBYguD/H9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T21:00:31Z"
    mac: ENC[AES256_GCM,data:ZoWkCqHyxWncBOL+eua1CWA35Zoq0w9Dk/yg0qCRzVqsqh1CPFHth6hKvBz4oeB6J/xa8aLvX6wpyPoN9Rzgl7gC11OcWqyjlLBwQVW+5AFE/EEaU09MVio4IhlebanHnanH6gn4Eg0uc7ccCOMEVSDC/UdkMldu4vDQcffu/y8=,iv:WijTp2cl3udjt2S0GLL+s1OIsK9ND6M1tj5VQdkZq5w=,tag:PvYoxGMKM4s9htj05lYF0w==,type:str]
    version: 3.13.1
