apiVersion: v1
kind: Secret
metadata:
    name: mattermost-initial-admin-password
    namespace: mattermost
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:u3FLV1BEMw==,iv:lYwyFUz4n1iOJrdCYFCBi+rYtfffs0YhQwr6jc1cDMk=,tag:lbdB03ZWXy2dXlFJ7RCZqQ==,type:str]
    email: ENC[AES256_GCM,data:wQW38potpKXpVJ2rrWkwp53W,iv:5XM5qjyiX7BD1TgQWSvvOWWcVhftArlrA1yAdZc3vyM=,tag:d2KHRXY24qbJRVrIM7OFjA==,type:str]
    password: ENC[AES256_GCM,data:FHVQDAgnjFNpRiblVYk2y4Un9EfGYfYBiVPjkWP/fxM=,iv:Yo4ZIZyFTx5FiQ08A6qk6fqQL4WknhR/HCSrsxjzatU=,tag:aPHyCaCPwS025oTlB/QAKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZkhDMmRxWFdrcWp3U05N
            MEJKSVdiZWIxRUM1VW4rRzlqN3JMek9hZUIwCklqMmVUT1N3QkVHL3h0bjl2ak5R
            UzBVTWs1K0dsZXZ5cUY1b3k1TWdSVUkKLS0tIGVQSVQ3RzQ4SnBQNW9KU2s2bVFn
            MTFkRXFXcG92NmF5cWFRcWR0YlRkclkKp93/OEuAid+BrqzyiFbTIZV5Bo8gubW8
            ruAywzjREt3gV7oekgrxogyWhDNzzhnPDBKNaRFwN8VQG2Vis7CqtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T08:05:38Z"
    mac: ENC[AES256_GCM,data:so7XX73nSqY+n8hbKEEHzsKlEmqzo+3mHrCGnRaGxtp10+pbIMk/KKp0XEdvvjMumr/3O3WSFwNxsoA1ikhv/JDk8MX2xMnSQ7Req4QR/JUBGz/WIzhN8orIBFsbhFBQTYE93pUUB09A8/0IR4yK9Gx8/zO1oe0JoAUDWyZod6M=,iv:vdLsx24qCSzMqdgDp2g/ADCi0duoHjq52P+A7Xz9AhA=,tag:Tj9P9lKhFrjQQyQENQWkCg==,type:str]
    version: 3.13.1
