apiVersion: v1
kind: Secret
metadata:
    name: openchamber-github
    namespace: openchamber
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:BFS9JloTGz6T1Dp2XhXKE4x4jX5Obod5yJXQsuimAlIJADAh+6i6YA==,iv:AdZwb5fMTiH66Ez38hamrJk16yt9QDVET8slIsKmRSY=,tag:lpchzZdYBDsN3neCUCiFvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLckNKcUJHKzN6Q29OOWQw
            eVdrd3NRQkV2a0N0aEkySy9BODFCTHRTa2hjCjQ5R0s1N0gwdVVkR05PUXlZOFZK
            b3crTGtLMFR0WTJlVVBWM3FWZDkwMDgKLS0tIGxQaUs2YXRXK3F2bnVkOVloWnBG
            ekpjeWRCcVNyMlFwdG9IU2IrMDU4dVkKKkvbLPLl+0+33KiDTh0E3Z2pco0K9TPt
            ORrlxApvJl/dSfeaH2lSNF/dEheyeTWlam9hMCCCzZcTEGu5yD29jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T21:33:46Z"
    mac: ENC[AES256_GCM,data:x23z2C5kw8+fAKrYsqnYfOzf6koAmWLRCPRks5o8IaK/QCKrvlj7yLTlxwk7TiaP2dt5/gMV/pZ1wvuqpz9ypRjzMDN8FNLrDzZ9Dw1RrXTwcaTsWSwpcHHLRr1J2DnCjllQAEi7r6h+N9/5+x/1YknkacVuwYXzo9FwpHepIe0=,iv:U7wtEY99kV5qPhOLTumZChuk5P7GK/VjXk3B/y9fJ7U=,tag:q2ALaZBS3yDY9ChOyv/6yg==,type:str]
    version: 3.13.3
