apiVersion: v1
kind: Secret
metadata:
    name: openchamber-minio-backup-creds
    namespace: openchamber
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Rw96NvE1noifw7ow12xVpNI92HrUhv4=,iv:TnpwzPEZUdqzsCU40trpXzIC+EYEOWqFiu++0YtUGqY=,tag:tUd7ZMFxqP73KxIwjLOxvw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Yz+mTyiATXp+2E0qCd8TEoWpBYR7ngc8NECPFMzB5V8Npc42wypRbw==,iv:RZiSwU7WnIc1MLNPaYzLzu6p3zItYAToGMUy/7QsEoE=,tag:JYOKyub2pH8DGxNyuG3srw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbm42SzVCWlJHUFc4TFIv
            ZEIzVnJwOVNrY1A3ay9ZMmtXbDR0bmVybEFrCkhwNDAyS3E4UW1oZW14WlpXZWcr
            R0pCTE5DaldqVlQyYW0weDFLZnhPZGsKLS0tIEhERUw0QWhHc1lPdXJaWmYwc2FQ
            UzkxZ3BUK0lBdXhYcUZkcllBVDB4VW8KkP8ExsXWSLYtg1ULuJEtlgpYR82HWI/d
            7ZNRzTqIc8EgEBSiFo5qG4w3t1mI4rDMvcdi+h3Clp91N4Crn6YTuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T05:48:25Z"
    mac: ENC[AES256_GCM,data:gNO7iwO2Du6GEEGzG1ru8BrlBf/jsR55Fncd+C/6cHzS1BXMs3/dYPLsydrxgyug1+xolQPrklYW7YiDqYJUpg+CJc+Y0s1/e46SDxWxXBDRuxEy2OmZy4WjapPcR8hPfVVlp3j7geiHhztqBVcW0AjWfIrO8owGrRFpSlcxOjg=,iv:U2aEgMChvppaz+tGOXhbOvD/BGwS7xTnLm7WPtQnA8E=,tag:9SudrH023k9lvmVNPV1SKg==,type:str]
    version: 3.13.3
