apiVersion: v1
kind: Secret
metadata:
    name: openchamber-tunnel-token
    namespace: openchamber
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:qHhUWbdm5sF3OERZEk+rvdYzikTB/FawGP3O27QJ/4V87iqfR/dcR2B/VwjqZIG1AG0KMVTPMBF25OEih8l1CLSuxxm9I8/aSWKVanbde6DlVpGewW+uX/WNMhVWMTeUYP5BaHNl3qTZNKd+KAvC79EHbWYJYMzW+yfy+V1vQmJnxB7dprV3G+q0RVfkNG4EVMmYEcPcDcXCgkXzjJpFseWVZAf6lNHxgSib/kXX/GDI701xtUibPQ==,iv:Ghzqf+xOUsTyhbrx/cjTMrnNAGqo4MOaSgq19v7GjQQ=,tag:Rzo3t2eSl+W/Dio60WwWOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTWRQWGgzaFhUeG83N1g1
            UFE2ODlSRFY5MktYdVdBVGxJdE5WZVcwc0YwCkU1aytOcjYwbGt1dGV5bE51ajlX
            UmFvV3I0aC9hbUVsd0FPRnJ4OWlJbGcKLS0tIFNvUGFEdkQrbUhpU0FEU0llb2hF
            VERkUEVpNU5QYm15SkpnNVZ0TGlhVmMKbSfPHtbuLwmFiLdEG9NODBSO6+ewXFbj
            FsISDsTTdsd6XsxcjapJNLZOhDTanV/FLJTl/Gb02hMwBaRUp9MVkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T20:05:23Z"
    mac: ENC[AES256_GCM,data:Fq8bdIQ1sbTgEBXS2uviqSxXgNJMKmYZll3A1Qd/BNsMK2Uh5/H3KzNVFw1oAPmC3pSmbknboMNzeghb/hTPRbLyLuNAlWvCGNWo3Eaj8Vn8AMIrPLq1Qi/Z0YOK4kQwlANoEpaeh02k4kCNczBvyW/Lxv4DVk/X+xPxmaRyNE8=,iv:gExpB8BJOLomU+PvtELmres1L2Cvht9VvhozrPls4pE=,tag:+lECOItQh7uN0F/JRpeKTg==,type:str]
    version: 3.13.3
