apiVersion: v1
kind: Secret
metadata:
    name: openchamber-secrets
    namespace: openchamber
type: Opaque
stringData:
    OPENCHAMBER_UI_PASSWORD: ENC[AES256_GCM,data:+Djko5tv/DHWKzHG2QOlcMbhrC7f+PMwfU2D6FCFxZI=,iv:zza91MK67jOwLqdLkmzCCKv8DFn6ORa/JDMciQSFLGU=,tag:f/UeaDnmb7/FpCuqYW0HSA==,type:str]
    OPENCODE_JWT_SECRET: ENC[AES256_GCM,data:v9DsRgm4tDqBX6qJTGAIHBcbM4vkhSE64K6mXYoifZ2GU6nL99BXRbsIa+HCJEmB7ZZQjlsS/zePhv+2V5J/qg==,iv:mXocN67HQzOPkyVTu700uw5NTJvXXdu/G7p85o1Mbwg=,tag:Hl45lcUDRnT+pDP1gtz+wg==,type:str]
    OPENCHAMBER_LITELLM_KEY: ENC[AES256_GCM,data:zkKBIiKG0w/UD+Xr7uU0xpVRQxxHj1gSnQ==,iv:X9q0IBbtLyCVOukNZfbAZKVBAgFZTy8lb3WJYSzNg54=,tag:iVBFq+ks830eslrSY4eN5A==,type:str]
    OPENVIKING_API_KEY: ENC[AES256_GCM,data:pai1gIvDLaoqKmo7bfdqZw==,iv:EkpHkZsfOuVKqDiLqvTneAULhbKhh6iY6sPu6DCi4rM=,tag:hkj6QWdFo8fvTsnJv2/AHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkM3BLVzh5dTc5ZDltN05S
            bEl5N3pNSmt2cmlrT3NrWHcycE5hN0o1NVFFCkxSUFBocUZZUmRLMXZuUFYvb3RR
            VG9paDE0UHVnWlQydWlEMVZudmc1R2cKLS0tIEs0YnBGVTFyV0t5YVZPbkM5MG8x
            SG9wSlNYK0pQbGhucldjZVRjazNtMHMKQ2POTfX0wr0UHsLcphtdl0Lvpvg5B5f8
            pdSLYEVLz0bqHpw3o2gA4NCJztEht0iNn5AX6OaNf/LInFP5TCjryw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T17:30:20Z"
    mac: ENC[AES256_GCM,data:3H4boSfktIYLBeyuJ0cF087gBRq1QHHuVJbtcCrEhYNHagEc5iQ+c6cWWr0O0X7QkvGjiFXeK58PFXVkOXHyASXejYE8DPFuN1mMRCZIkg7RrqVipDiXg0s9PQGLW/3pVjLuAKeqMfBwj09pKk+PYcVzJeaoU1A7vIv/GqWeAM0=,iv:y0CptvqF6vpCGRnUc/ZGJuSp+rAOdP0AO/i4CyHrAMI=,tag:Z30KDpq35Uvi4YH6ye177A==,type:str]
    version: 3.13.3
