apiVersion: v1
kind: Secret
metadata:
    name: openchamber-secrets
    namespace: openchamber
type: Opaque
stringData:
    OPENCHAMBER_UI_PASSWORD: ENC[AES256_GCM,data:2U1LX725uLhp9ykkO06vcGY7JJWP22er,iv:rtNzAqqrdMcH2ry9diIdaTKkctdCHl9dCAe/PC2L6X8=,tag:VZeTGIizP7Dp2LstMfYYfw==,type:str]
    OPENCODE_JWT_SECRET: ENC[AES256_GCM,data:/KRyBOncyj0sY1LKtn+7SOH01rbmFy1PrGMbPoAKuW6yc+vP3rvFje+nQGh6r/LgRvoV3+LLqb40L8xHrL65gg==,iv:jYRClxR164Qa0hA2Frng0gVNStulmRS/rJRUwV4ZoH4=,tag:rZPZU/3dQ/+AKMY/uJxBxw==,type:str]
    OPENCHAMBER_LITELLM_KEY: ENC[AES256_GCM,data:I7KNAOXa7KZZKsFPpJEWGlcujt+QrKpZUg==,iv:ZKs2xUpp7hOSu8CRpbFJCWaw+d+Z5PgyLD0fP2Oo6+o=,tag:A6cZ3cVT2GSu8QKHafTsGg==,type:str]
    OPENVIKING_API_KEY: ENC[AES256_GCM,data:p6xXqps7ZbZfiWVdvUjV6g==,iv:Me4uYdh14qY97rLaJ0QhoZBBjqrUJTP64jkFEih+a88=,tag:a3wKNOH4pVVj+/6uLrmmCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYWpRVzlET0NtWXBCdmdj
            d05rdWZzWTdwbENHcWtReWZyc2RvRkFsM1Q0Ck0xdHNZdUEzczNScE5ncjZSbHVn
            MlR3QVRLVXAvSlZvTm9GRmUrQXZ4ZUkKLS0tIEFDbWZTV2xnNEdQZStjTkJZNFVw
            aHlwZFVDY2gzMWQ1NnB2eFc2b0N5TlkKj7xA//Mw2K3fO2O596pOD2NWcA87BjPq
            fV0mdUtpxcBnmvIpVdkp6tuC7jH0ZefEbr3bxxD7jv+rOOTAkayVug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T08:23:07Z"
    mac: ENC[AES256_GCM,data:y/tdm6mVpZ43IB1LI33mm+JUvuJPyO0E5b3X+BTCIRrJdUJznXvu3NcwZxq7rp2rW8Tzj70P/n/yyvSmG2WIRv/mQi5IJqb5JWwyWvW2q9zEiXcKmXoY0cXttIx/D9dgZwtb8JtUEcTCsLJmJHu9jModdPZiy6bVfeZ5f4JJsw4=,iv:pWWqHQ/x5609AWzVc73M9FHryo9e2dP3cXAhRDHSfIg=,tag:EsHKxi+Eo0G2VMXkzw1CBA==,type:str]
    version: 3.13.1
