apiVersion: v1
kind: Secret
metadata:
    name: openchamber-tunnel-token
    namespace: openchamber
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:rka2jgr596RH3wIdhFbk6EeJBofN4O8IsORnKBNKoMXUwLoA,iv:nYD57E0XGigMKrdjEc7oRbDPwYkJlTeA6dEtLy/DSXY=,tag:i/BG04OtYDU0HKyK8DchWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTWRQWGgzaFhUeG83N1g1
            UFE2ODlSRFY5MktYdVdBVGxJdE5WZVcwc0YwCkU1aytOcjYwbGt1dGV5bE51ajlX
            UmFvV3I0aC9hbUVsd0FPRnJ4OWlJbGcKLS0tIFNvUGFEdkQrbUhpU0FEU0llb2hF
            VERkUEVpNU5QYm15SkpnNVZ0TGlhVmMKbSfPHtbuLwmFiLdEG9NODBSO6+ewXFbj
            FsISDsTTdsd6XsxcjapJNLZOhDTanV/FLJTl/Gb02hMwBaRUp9MVkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T17:30:49Z"
    mac: ENC[AES256_GCM,data:sVLRFzm6wcMnh4rNfujODhO8hFzG5+2iD81CXAg44jsOR4RNEriY0hENYW2aXxOdad3n1amvI6JoLIN7KSGZ2WdKV3Kz0vE7McRikGV2duyoFllP9pdh1xW5I/D3u9YqjEs1MfT3vpxhQNN0hf84iExHE6SCMC4T/3cIS1Ny2Y0=,iv:l9uKq8OQC1ugZy2fz8w15l82FiUgUXO0u7QszFstzZQ=,tag:GOLvmhoRfSeHKz91QR7qNA==,type:str]
    version: 3.13.3
