apiVersion: v1
kind: Secret
metadata:
    name: openchamber-secrets
    namespace: openchamber
type: Opaque
stringData:
    OPENCHAMBER_UI_PASSWORD: ENC[AES256_GCM,data:p3x3J4BlUsCI7RJDJXRgfkUh334F4lMX,iv:Zcg8fRdhCgH7z+RoYBXWj2jvGblF+jkEgaLo/NoFR3U=,tag:Brj/wKEvUGyPAQKl2RSa1A==,type:str]
    OPENCODE_JWT_SECRET: ENC[AES256_GCM,data:D/BpEI62jC1RREbmj+y5xRN3TwZHRlM8cd8wAjrRcRYsz/p4UbJqYdQ+Lql1s8UdQJTs4xs8wQLSuop3Vz7QhA==,iv:aTAoP2yex5ZR+aUtxbJy40ZBIaYpbspGxKRGRGkZSGQ=,tag:fvsqlB3K/lOTtmAUSmlQQw==,type:str]
    OPENCHAMBER_LITELLM_KEY: ENC[AES256_GCM,data:WRMv57bptO63keCfUEphncO0O42Ot9eFmw==,iv:YvGKGBzHkj6vvnxCKC4dKIUEVPyJVKdx/NyRqc03U4Q=,tag:MTVTeYdpvECe3hHHfzfdDw==,type:str]
    OPENVIKING_API_KEY: ENC[AES256_GCM,data:808EV0glaBinIDxanRS5Gw==,iv:7WIbkXYSfkJlxqiWdHCAn/dx4HugNP1oc9G1zXruvn8=,tag:vPBVXgQ0fqb3jldtKRUpIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMTdKT01zcG1jYzN2ajB1
            bk9xWFlENS9GUnczR1IwTm5NenZZQm9sQkVvCllGR3ZzWkd5UHFTN3lIdHY5Z0R5
            RzROeWZ2bHNwa1kxU3lBcjFVZVI0UEkKLS0tIGtrUzVEaGdJK1RpaDBiandDblpC
            cVc3MlBsVC9EYS82aVYyeVdzNE5UTlkKiRtfLE9p4BwPvGaMtGJbrUateUYxGLn2
            H3azwLcDtaca5RxvP8S3viSLn+Zx5D6g/FiuytSQpLx26WY8tTvUrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195fednlfd8q35tvyvf7umlseu4ez37k2m2d0wjawmje6nr9kzgyquhau9s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T08:39:07Z"
    mac: ENC[AES256_GCM,data:oIb+LYhQQtfKlws/D9c6rgTYTtIX3TSDBtklHAIdlkz08uZSj7pP5dUAdwkZZOPfWRNMCjoHk9bBBAUM3Dp0XjlaEL7vaQTgDpcgsEqSVfjuupoXq6T6rbbYMwGJJ2pbagpDdL+7G53QZayyZUhmm3PwJ0+fMKA6Oe5ejWCKCYo=,iv:1kmSgoDI20PHozhEoVCDvZBEY+DOh28aWpbP1wkuY44=,tag:KYJdMJUY8PitmzdQUbpdFQ==,type:str]
    version: 3.13.1
