---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CNPG Operator
  - cnpg/helm-repository.yaml
  - cnpg/helm-release.yaml
  # Mattermost HelmRepository (needed for HelmRelease in apps)
  - mattermost/helm-repository.yaml
