---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Mattermost namespace
  - mattermost/namespace.yaml
  # SOPS-encrypted secrets
  - mattermost/mattermost-db-credentials.sops.yaml
  - mattermost/minio-backup-creds.sops.yaml
  - mattermost/mattermost-minio-creds.sops.yaml
  - mattermost/chat-tunnel-token.sops.yaml
  - mattermost/mattermost-initial-admin-password.sops.yaml
  # CNPG Cluster for Mattermost Postgres
  - mattermost/postgres-cluster.yaml
  - mattermost/scheduled-backup.yaml
  # Mattermost HelmRelease
  - mattermost/mattermost-helm-release.yaml
  # Cloudflare Tunnel for chat.voitech.dev
  - mattermost/cloudflared-chat-deployment.yaml
  # Nextcloud namespace
  - nextcloud/namespace.yaml
  # SOPS-encrypted secrets
  - nextcloud/nextcloud-admin-credentials.sops.yaml
  - nextcloud/nextcloud-db-credentials.sops.yaml
  - nextcloud/nextcloud-minio-creds.sops.yaml
  - nextcloud/nextcloud-backup-creds.sops.yaml
  - nextcloud/nextcloud-cloudflare-token.sops.yaml
  # NFS PV/PVCs
  - nextcloud/nextcloud-html-pv.yaml
  - nextcloud/nextcloud-html-pvc.yaml
  - nextcloud/nextcloud-data-pv.yaml
  - nextcloud/nextcloud-data-pvc.yaml
  # CNPG Cluster for Nextcloud
  - nextcloud/postgres-cluster.yaml
  - nextcloud/scheduled-backup.yaml
  # Nextcloud HelmRelease
  - nextcloud/nextcloud-helm-release.yaml
  # Cloudflare Tunnel for photos.voitech.dev
  - nextcloud/cloudflared-deployment.yaml
