---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: arr-box
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.4.0.5397-ls153
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          env:
            - name: HTTP_PROXY
              value: "http://gluetun.arr-stack.svc.cluster.local:8888"
            - name: HTTPS_PROXY
              value: "http://gluetun.arr-stack.svc.cluster.local:8888"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,cluster.local,.arr-stack.svc.cluster.local,openmediavault.local"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
